

export type DistributionName='bernoulli'|'binomial'|'normal'|'standard-normal'|'lognormal'|'student-t';
export function validateProbability(p:number){return Number.isFinite(p)&&p>=0&&p<=1}
export function bernoulliMoments(p:number){if(!validateProbability(p))return{error:'Probability must be between 0 and 1.'};return{mean:p,variance:p*(1-p)}}
function logFactorial(n:number){let total=0;for(let i=2;i<=n;i++)total+=Math.log(i);return total}
export function binomialProbability(n:number,p:number,x:number){if(!Number.isInteger(n)||n<0)return{error:'Trials must be a non-negative integer.'};if(!Number.isInteger(x)||x<0||x>n)return{error:'Successes must be an integer from 0 through n.'};if(!validateProbability(p))return{error:'Probability must be between 0 and 1.'};if(p===0)return{value:x===0?1:0};if(p===1)return{value:x===n?1:0};const logP=logFactorial(n)-logFactorial(x)-logFactorial(n-x)+x*Math.log(p)+(n-x)*Math.log(1-p);return{value:Math.exp(logP)}}
export function binomialCdf(n:number,p:number,x:number){if(!Number.isInteger(x))return{error:'Successes must be an integer.'};if(x<0)return{value:0};if(x>=n&&Number.isInteger(n)&&validateProbability(p))return{value:1};let total=0;for(let k=0;k<=x;k++){const r=binomialProbability(n,p,k);if('error'in r)return{error:r.error};total+=r.value}return{value:Math.min(1,total)}}
export function binomialMoments(n:number,p:number){if(!Number.isInteger(n)||n<0||!validateProbability(p))return{error:'Use a non-negative integer n and probability from 0 to 1.'};return{mean:n*p,variance:n*p*(1-p)}}
export function zScore(x:number,mean:number,standardDeviation:number){if(!Number.isFinite(standardDeviation)||standardDeviation<=0)return{error:'Standard deviation must be greater than zero.'};if(!Number.isFinite(x)||!Number.isFinite(mean))return{error:'Observation and mean must be finite.'};return{value:(x-mean)/standardDeviation}}
export function normalCdf(z:number){if(!Number.isFinite(z))return z===Infinity?1:z===-Infinity?0:NaN;const sign=z<0?-1:1;const x=Math.abs(z)/Math.SQRT2;const t=1/(1+.3275911*x);const erf=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x);return .5*(1+sign*erf)}
export function normalProbability(x:number,mean:number,standardDeviation:number){const z=zScore(x,mean,standardDeviation);if('error'in z)return{error:z.error};return{z:z.value,lower:normalCdf(z.value),upper:1-normalCdf(z.value)}}
export function lognormalMoments(mu:number,sigma:number){if(!Number.isFinite(sigma)||sigma<0)return{error:'Log standard deviation cannot be negative.'};const mean=Math.exp(mu+sigma*sigma/2);return{mean,variance:(Math.exp(sigma*sigma)-1)*Math.exp(2*mu+sigma*sigma)}}
export const zCritical=(confidence:number)=>confidence===.9?1.644854:confidence===.95?1.959964:confidence===.99?2.575829:null;
export function tCritical(confidence:number,degreesOfFreedom:number){const z=zCritical(confidence);if(z===null)return{error:'Confidence level must be 90%, 95%, or 99%.'};if(!Number.isInteger(degreesOfFreedom)||degreesOfFreedom<1)return{error:'Degrees of freedom must be a positive integer.'};const v=degreesOfFreedom;const z2=z*z;const value=z+(z*z2+z)/(4*v)+(5*z*z2*z2+16*z*z2+3*z)/(96*v*v)+(3*z*z2*z2*z2+19*z*z2*z2+17*z*z2-15*z)/(384*v*v*v);return{value}}
