

import {normalCdf} from './distributionService';
export type Tail='lower'|'upper'|'two';
export type TestDistribution='normal'|'t';
function logGamma(z:number):number{const c=[676.5203681218851,-1259.1392167224028,771.3234287776531,-176.6150291621406,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=.9999999999998099;for(let i=0;i<c.length;i++)x+=c[i]/(z+i+1);const t=z+c.length-.5;return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function betaFraction(a:number,b:number,x:number){const qab=a+b,qap=a+1,qam=a-1;let c=1,d=1-qab*x/qap;if(Math.abs(d)<3e-14)d=3e-14;d=1/d;let h=d;for(let m=1;m<=200;m++){const m2=2*m;let aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<3e-14)d=3e-14;c=1+aa/c;if(Math.abs(c)<3e-14)c=3e-14;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<3e-14)d=3e-14;c=1+aa/c;if(Math.abs(c)<3e-14)c=3e-14;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break}return h}
function regularizedBeta(x:number,a:number,b:number){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log(1-x));return x<(a+1)/(a+b+2)?bt*betaFraction(a,b,x)/a:1-bt*betaFraction(b,a,1-x)/b}
export function studentTCdf(t:number,df:number){if(!Number.isFinite(t)||!Number.isInteger(df)||df<1)return NaN;const x=df/(df+t*t);const half=.5*regularizedBeta(x,df/2,.5);return t>=0?1-half:half}
export function testPValue(statistic:number,tail:Tail,distribution:TestDistribution,df?:number){if(!Number.isFinite(statistic))return{error:'Test statistic must be finite.'};if(distribution==='t'&&(!Number.isInteger(df)||df!<1))return{error:'Degrees of freedom must be a positive integer.'};const cdf=distribution==='normal'?normalCdf(statistic):studentTCdf(statistic,df!);const p=tail==='lower'?cdf:tail==='upper'?1-cdf:2*Math.min(cdf,1-cdf);return{value:Math.min(1,Math.max(0,p))}}
export function criticalValues(alpha:number,tail:Tail,distribution:TestDistribution,df?:number){if(!Number.isFinite(alpha)||alpha<=0||alpha>=1)return{error:'Significance level must be between 0 and 1.'};if(distribution==='t'&&(!Number.isInteger(df)||df!<1))return{error:'Degrees of freedom must be a positive integer.'};const target=tail==='two'?1-alpha/2:1-alpha;let lo=-12,hi=12;for(let i=0;i<100;i++){const mid=(lo+hi)/2;const cdf=distribution==='normal'?normalCdf(mid):studentTCdf(mid,df!);if(cdf<target)lo=mid;else hi=mid}const c=(lo+hi)/2;return tail==='lower'?{lower:-c,upper:null}:tail==='upper'?{lower:null,upper:c}:{lower:-c,upper:c}}
export function hypothesisDecision(input:{statistic:number;alpha:number;tail:Tail;distribution:TestDistribution;df?:number}){const p=testPValue(input.statistic,input.tail,input.distribution,input.df);if('error'in p)return{error:p.error};const critical=criticalValues(input.alpha,input.tail,input.distribution,input.df);if('error'in critical)return{error:critical.error};const reject=p.value<=input.alpha;return{pValue:p.value,...critical,decision:reject?'Reject the null hypothesis':'Fail to reject the null hypothesis',reject}}
