import {beforeEach,describe,expect,it} from 'vitest'; import {completionPercent,defaultProgress,parseProgress,quizScore} from './progressService';
describe('progress storage',()=>{beforeEach(()=>localStorage.clear());it('provides safe defaults',()=>{expect(parseProgress(null)).toEqual(defaultProgress())});it('handles malformed JSON',()=>{expect(parseProgress('{broken')).toEqual(defaultProgress())});it('calculates completion safely',()=>{expect(completionPercent(['a','b'],4)).toBe(50);expect(completionPercent([],0)).toBe(0)});it('scores quiz attempts',()=>{expect(quizScore([{correct:true},{correct:false},{correct:true}])).toBe(67)})});

describe('2027 Quantitative migration',()=>{
 const legacy=()=>JSON.stringify({...defaultProgress(),version:1,curriculumMigration:undefined,legacyNotes:undefined,completedLessons:['quant-distributions-07','quant-tvm-04'],bookmarkedLessons:['quant-distributions-07','quant-tvm-04'],notes:{'quant-distributions-07':'My normal-distribution note','quant-tvm-04':'Keep me'},quizAttempts:[{questionId:'q07-01',lessonId:'quant-distributions-07',correct:true,selectedIndex:0,confidence:'confident',answeredAt:'2026-01-01'}],flashcardReviews:{'fc07-01':{rating:'good',reviewedAt:'2026-01-01'}}});
 it('transfers distribution completion without completing portfolio',()=>{const p=parseProgress(legacy());expect(p.completedLessons).toContain('quant-probability-06');expect(p.completedLessons).not.toContain('quant-distributions-07');expect(p.completedLessons).toContain('quant-tvm-04')});
 it('removes the semantic bookmark and preserves both notes',()=>{const p=parseProgress(legacy());expect(p.bookmarkedLessons).not.toContain('quant-distributions-07');expect(p.bookmarkedLessons).toContain('quant-tvm-04');expect(p.notes['quant-probability-06']).toContain('normal-distribution');expect(p.legacyNotes['quant-distributions-07@pre-2027-portfolio']).toContain('normal-distribution')});
 it('retains history but marks it legacy under LM6',()=>{const p=parseProgress(legacy());expect(p.quizAttempts[0]).toMatchObject({lessonId:'quant-probability-06',legacyOfficialModuleId:'legacy-distributions'});expect(p.flashcardReviews['fc07-01'].rating).toBe('good')});
 it('is idempotent',()=>{const once=parseProgress(legacy());expect(parseProgress(JSON.stringify(once))).toEqual(once)});
 it('deduplicates existing LM6 completion',()=>{const p=parseProgress(JSON.stringify({...JSON.parse(legacy()),completedLessons:['quant-distributions-07','quant-probability-06']}));expect(p.completedLessons.filter(x=>x==='quant-probability-06')).toHaveLength(1)});
 it('preserves attempt confidence and timestamp exactly',()=>{const p=parseProgress(legacy());expect(p.quizAttempts[0]).toMatchObject({confidence:'confident',answeredAt:'2026-01-01',correct:true,selectedIndex:0})});
 it('sanitizes a malformed root safely',()=>{expect(parseProgress('[]')).toEqual(defaultProgress());expect(parseProgress('{"version":1,"completedLessons":"bad","bookmarkedLessons":[]}')).toEqual(defaultProgress())});
});
