import type {Activity,Confidence,FlashcardRating,ProgressState,QuizAttempt} from '../data/types';
export const STORAGE_KEY='cfa-pass-progress';
const LEGACY_DISTRIBUTION='quant-distributions-07',CANONICAL_DISTRIBUTION='quant-probability-06',LEGACY_NOTE_KEY='quant-distributions-07@pre-2027-portfolio';
export const defaultProgress=():ProgressState=>({version:2,curriculumMigration:'2027-quant-v1',completedLessons:[],bookmarkedLessons:[],notes:{},legacyNotes:{},quizAttempts:[],flashcardReviews:{},lastOpenedLesson:null,recentlyViewedLessons:[],lastCompletedLesson:null,examDate:'',dailyQuestionGoal:10,theme:'light',recentActivity:[]});
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string');
const unique=(values:string[])=>[...new Set(values)];
type LegacyProgress=Omit<ProgressState,'version'|'curriculumMigration'|'legacyNotes'|'quizAttempts'>&{version:1;quizAttempts:QuizAttempt[];legacyNotes?:Record<string,string>};
export function migrateQuant2027(state:LegacyProgress):ProgressState{
 const hadDistribution=state.completedLessons.includes(LEGACY_DISTRIBUTION),distributionNote=state.notes[LEGACY_DISTRIBUTION];
 const completed=state.completedLessons.filter(id=>id!==LEGACY_DISTRIBUTION);if(hadDistribution&&!completed.includes(CANONICAL_DISTRIBUTION))completed.push(CANONICAL_DISTRIBUTION);
 const notes={...state.notes};if(distributionNote){const current=notes[CANONICAL_DISTRIBUTION]?.trim();notes[CANONICAL_DISTRIBUTION]=current?`${current}\n\nMigrated distribution notes:\n${distributionNote}`:distributionNote}delete notes[LEGACY_DISTRIBUTION];
 const replaceLegacy=(id:string|null)=>id===LEGACY_DISTRIBUTION?CANONICAL_DISTRIBUTION:id;
 return{...defaultProgress(),...state,version:2,curriculumMigration:'2027-quant-v1',completedLessons:unique(completed),bookmarkedLessons:state.bookmarkedLessons.filter(id=>id!==LEGACY_DISTRIBUTION),notes,legacyNotes:{...(state.legacyNotes??{}),...(distributionNote?{[LEGACY_NOTE_KEY]:distributionNote}:{})},quizAttempts:state.quizAttempts.map(attempt=>attempt.lessonId===LEGACY_DISTRIBUTION?{...attempt,lessonId:CANONICAL_DISTRIBUTION,curriculumVersion:'legacy-pre-2027-remediation',legacyOfficialModuleId:'legacy-distributions'}:attempt),lastOpenedLesson:replaceLegacy(state.lastOpenedLesson),recentlyViewedLessons:unique(state.recentlyViewedLessons.map(id=>replaceLegacy(id)!).filter(Boolean)).slice(0,5),lastCompletedLesson:replaceLegacy(state.lastCompletedLesson)};
}
export function parseProgress(raw:string|null):ProgressState{if(!raw)return defaultProgress();try{const x:unknown=JSON.parse(raw);if(!x||typeof x!=='object')return defaultProgress();const p=x as Omit<Partial<ProgressState>,'version'>&{version?:number};if(!strings(p.completedLessons)||!strings(p.bookmarkedLessons))return defaultProgress();if(p.version===1)return migrateQuant2027({...defaultProgress(),...p,version:1,quizAttempts:Array.isArray(p.quizAttempts)?p.quizAttempts:[]} as LegacyProgress);if(p.version!==2)return defaultProgress();return{...defaultProgress(),...p,version:2,curriculumMigration:'2027-quant-v1',notes:p.notes&&typeof p.notes==='object'?p.notes:{},legacyNotes:p.legacyNotes&&typeof p.legacyNotes==='object'?p.legacyNotes:{},quizAttempts:Array.isArray(p.quizAttempts)?p.quizAttempts:[],recentActivity:Array.isArray(p.recentActivity)?p.recentActivity:[],recentlyViewedLessons:strings(p.recentlyViewedLessons)?p.recentlyViewedLessons.slice(0,5):[],lastCompletedLesson:typeof p.lastCompletedLesson==='string'?p.lastCompletedLesson:null};}catch{return defaultProgress();}}
export const loadProgress=()=>parseProgress(localStorage.getItem(STORAGE_KEY));
export const saveProgress=(state:ProgressState)=>localStorage.setItem(STORAGE_KEY,JSON.stringify(state));
export const completionPercent=(completed:string[],total:number)=>total<=0?0:Math.round(Math.min(completed.length,total)/total*100);
export const quizScore=(attempts:Pick<QuizAttempt,'correct'>[])=>attempts.length?Math.round(attempts.filter(a=>a.correct).length/attempts.length*100):0;
export function activity(type:Activity['type'],label:string):Activity{return{id:crypto.randomUUID(),type,label,timestamp:new Date().toISOString()};}
export function recordAnswer(state:ProgressState,input:{questionId:string;lessonId:string;correct:boolean;selectedIndex:number;confidence:Confidence}):ProgressState{return{...state,quizAttempts:[...state.quizAttempts,{...input,answeredAt:new Date().toISOString(),curriculumVersion:'2027'}],recentActivity:[activity('quiz',input.correct?'Answered correctly':'Reviewed an incorrect answer'),...state.recentActivity].slice(0,12)};}
export function rateCard(state:ProgressState,id:string,rating:FlashcardRating):ProgressState{return{...state,flashcardReviews:{...state.flashcardReviews,[id]:{rating,reviewedAt:new Date().toISOString()}},recentActivity:[activity('flashcard',`Reviewed a flashcard: ${rating}`),...state.recentActivity].slice(0,12)};}
