import {describe,expect,it} from 'vitest';
import returns from '../data/questions/quantitative.json';import benchmarking from '../data/questions/quantitative-benchmarking.json';import tvm from '../data/questions/quantitative-tvm.json';import statistics from '../data/questions/quantitative-statistics.json';import probability from '../data/questions/quantitative-probability.json';import sampling from '../data/questions/quantitative-sampling.json';import hypothesis from '../data/questions/quantitative-hypothesis.json';import portfolio from '../data/questions/quantitative-distributions.json';import simulation from '../data/questions/quantitative-simulation.json';import regression from '../data/questions/quantitative-regression.json';import dataAi from '../data/questions/quantitative-data-ai.json';
import {moduleBreakdown,selectBalancedAssessment} from './assessmentService';import type {Question} from '../data/types';
const questions=[...returns,...benchmarking,...tvm,...statistics,...probability,...sampling,...hypothesis,...portfolio,...simulation,...regression,...dataAi] as unknown as Question[];

describe('v1.6.6 Quantitative certification',()=>{
 const selected=selectBalancedAssessment(questions,90,166);
 it('builds the real 90-question official comprehensive assessment',()=>{expect(selected).toHaveLength(90);expect(new Set(selected.map(q=>q.officialModuleId)).size).toBe(11);expect(selected.every(q=>!q.supplementary)).toBe(true)});
 it('balances official modules and samples both LM7 subdivisions',()=>{const counts=[...new Set(selected.map(q=>q.officialModuleId))].map(id=>selected.filter(q=>q.officialModuleId===id).length);expect(Math.max(...counts)-Math.min(...counts)).toBeLessThanOrEqual(1);const lm7=selected.filter(q=>q.officialModuleId==='QM-LM7');expect(new Set(lm7.map(q=>q.subdivision))).toEqual(new Set(['A','B']))});
 it('uses portfolio content in LM8 and excludes LM11 metrics',()=>{expect(selected.filter(q=>q.officialModuleId==='QM-LM8').every(q=>q.lessonId==='quant-distributions-07'&&!/normal distribution|binomial/i.test(q.stem))).toBe(true);expect(selected.filter(q=>q.officialModuleId==='QM-LM11').every(q=>!q.stem.startsWith('SUPPLEMENTARY:'))).toBe(true)});
 it('is deterministic and reports LM7 once',()=>{expect(selectBalancedAssessment(questions,90,166).map(q=>q.id)).toEqual(selected.map(q=>q.id));const answers=selected.map(q=>({questionId:q.id,lessonId:q.lessonId,correct:true,confidence:'confident' as const}));expect(Object.keys(moduleBreakdown(answers))).toHaveLength(11);expect(moduleBreakdown(answers)['QM-LM7'].answered).toBe(selected.filter(q=>q.officialModuleId==='QM-LM7').length)});
});
