import {useEffect,useState} from 'react';
import {economicsLessonIds} from '../content/economicsCurriculum';
import {fsaLessonIds} from '../content/fsaCurriculum';
import {corporateIssuersLessonIds} from '../content/corporateIssuersCurriculum';
const questionModules=import.meta.glob('../data/questions/*.json');
const cardModules=import.meta.glob('../data/flashcards/*.json');
const formulaModules=import.meta.glob('../data/formulas/*.json');
type Classified={officialModuleId?:string;lessonId?:string;relatedLessonId?:string;supplementary?:boolean};
async function load(modules:Record<string,()=>Promise<unknown>>){const loaded=await Promise.all(Object.values(modules).map(fn=>fn()));return loaded.flatMap(module=>(module as {default:Classified[]}).default??[])}
export function useContentStats(){const[state,setState]=useState({questions:0,flashcards:0,formulas:0,officialQuantQuestions:0,officialQuantFlashcards:0,officialQuantFormulas:0,officialEconomicsQuestions:0,officialEconomicsFlashcards:0,officialEconomicsFormulas:0,officialFsaQuestions:0,officialFsaFlashcards:0,officialFsaFormulas:0,officialCorporateIssuersQuestions:0,officialCorporateIssuersFlashcards:0,officialCorporateIssuersFormulas:0,loading:true});useEffect(()=>{let active=true;Promise.all([load(questionModules),load(cardModules),load(formulaModules)]).then(([questions,flashcards,formulas])=>{if(!active)return;const official=(items:Classified[])=>items.filter(item=>item.officialModuleId?.startsWith('QM-LM')&&item.supplementary!==true).length;const officialEconomics=(items:Classified[])=>items.filter(item=>economicsLessonIds.includes(item.lessonId??item.relatedLessonId??'')&&item.supplementary!==true).length;const officialFsa=(items:Classified[])=>items.filter(item=>fsaLessonIds.includes(item.lessonId??item.relatedLessonId??'')&&item.supplementary!==true).length;const officialCorporateIssuers=(items:Classified[])=>items.filter(item=>corporateIssuersLessonIds.includes(item.lessonId??item.relatedLessonId??'')&&item.supplementary!==true).length;setState({questions:questions.length,flashcards:flashcards.length,formulas:formulas.length,officialQuantQuestions:official(questions),officialQuantFlashcards:official(flashcards),officialQuantFormulas:official(formulas),officialEconomicsQuestions:officialEconomics(questions),officialEconomicsFlashcards:officialEconomics(flashcards),officialEconomicsFormulas:officialEconomics(formulas),officialFsaQuestions:officialFsa(questions),officialFsaFlashcards:officialFsa(flashcards),officialFsaFormulas:officialFsa(formulas),officialCorporateIssuersQuestions:officialCorporateIssuers(questions),officialCorporateIssuersFlashcards:officialCorporateIssuers(flashcards),officialCorporateIssuersFormulas:officialCorporateIssuers(formulas),loading:false})});return()=>{active=false}},[]);return state}
