import {useEffect,useMemo,useState} from 'react';import {lessons} from '../content/lessonManifest';import {topics} from '../content/curriculum';import type {Flashcard,Formula,Question} from '../data/types';import {buildSearchIndex,matchSearch} from '../services/searchService';
type SearchData={formulas:Formula[];cards:Flashcard[];questions:Question[];markdown:Record<string,string>};
const empty:SearchData={formulas:[],cards:[],questions:[],markdown:{}};
const moduleDefault=(value:unknown)=>(value as {default:unknown[]}).default;
export function useSearch(query:string){const[data,setData]=useState<SearchData>(empty);useEffect(()=>{let active=true;Promise.all([
 Promise.all([import('../data/formulas/quantitative.json'),import('../data/formulas/quantitative-modules-3-4.json'),import('../data/formulas/quantitative-modules-5-6.json'),import('../data/formulas/quantitative-modules-7-8.json'),import('../data/formulas/quantitative-modules-9-10.json'),import('../data/formulas/quantitative-modules-11-12.json'),import('../data/formulas/economics-firm-market-01.json'),import('../data/formulas/economics-02-understanding-business-cycles.json'),import('../data/formulas/economics-03-fiscal-policy.json'),import('../data/formulas/economics-04-monetary-policy.json'),import('../data/formulas/economics-06-international-trade.json'),import('../data/formulas/economics-07-capital-flows-and-the-fx-market.json'),import('../data/formulas/economics-08-exchange-rate-calculations.json')]),
 Promise.all([import('../data/flashcards/quantitative.json'),import('../data/flashcards/quantitative-modules-3-4.json'),import('../data/flashcards/quantitative-statistics.json'),import('../data/flashcards/quantitative-probability.json'),import('../data/flashcards/quantitative-modules-7-8.json'),import('../data/flashcards/quantitative-modules-9-10.json'),import('../data/flashcards/quantitative-modules-11-12.json'),import('../data/flashcards/economics-firm-market-01.json'),import('../data/flashcards/economics-02-understanding-business-cycles.json'),import('../data/flashcards/economics-03-fiscal-policy.json'),import('../data/flashcards/economics-04-monetary-policy.json'),import('../data/flashcards/economics-05-introduction-to-geopolitics.json'),import('../data/flashcards/economics-06-international-trade.json'),import('../data/flashcards/economics-07-capital-flows-and-the-fx-market.json'),import('../data/flashcards/economics-08-exchange-rate-calculations.json')]),
 Promise.all([import('../data/questions/quantitative.json'),import('../data/questions/quantitative-benchmarking.json'),import('../data/questions/quantitative-tvm.json'),import('../data/questions/quantitative-statistics.json'),import('../data/questions/quantitative-probability.json'),import('../data/questions/quantitative-distributions.json'),import('../data/questions/quantitative-sampling.json'),import('../data/questions/quantitative-hypothesis.json'),import('../data/questions/quantitative-regression.json'),import('../data/questions/quantitative-simulation.json'),import('../data/questions/quantitative-data-ai.json'),import('../data/questions/economics-firm-market-01.json'),import('../data/questions/economics-02-understanding-business-cycles.json'),import('../data/questions/economics-03-fiscal-policy.json'),import('../data/questions/economics-04-monetary-policy.json'),import('../data/questions/economics-05-introduction-to-geopolitics.json'),import('../data/questions/economics-06-international-trade.json'),import('../data/questions/economics-07-capital-flows-and-the-fx-market.json'),import('../data/questions/economics-08-exchange-rate-calculations.json')]),
 Promise.all(lessons.map(l=>fetch(`${import.meta.env.BASE_URL}${l.filePath}`).then(r=>r.ok?r.text():'')))
 ]).then(([formulaModules,cardModules,questionModules,markdown])=>{if(!active)return;setData({formulas:formulaModules.flatMap(moduleDefault) as unknown as Formula[],cards:cardModules.flatMap(moduleDefault) as Flashcard[],questions:questionModules.flatMap(moduleDefault) as Question[],markdown:Object.fromEntries(lessons.map((lesson,index)=>[lesson.id,markdown[index]??'']))})});return()=>{active=false}},[]);const index=useMemo(()=>buildSearchIndex(topics,lessons,data.formulas,data.cards,data.markdown,data.questions),[data]);return matchSearch(index,query)}
