import {useState} from 'react';
import {Link} from 'react-router-dom';
import {useMockLibrary} from '../hooks/useMockLibrary';
import {averageConfidence,filterMocksByYear,latestAttempt,loadMockProgress,mockYearForAttempt,scoreAttempt,sortMocks,weakQuestions} from '../mocks/mockService';

export function MockExamPage(){
  const library=useMockLibrary(),[progress]=useState(loadMockProgress),[year,setYear]=useState('all'),[provider,setProvider]=useState('all'),[status,setStatus]=useState('all');
  if(library===undefined)return <p role="status" className="card">Loading private mock library…</p>;
  if(!library)return <><h1>Mock Exams</h1><section className="card mt-6"><h2>Private mock library not installed.</h2><p className="muted mt-2">Mock source material is never included in public builds. Run the local private extraction workflow and use the development server to enable this center.</p></section></>;
  const years=[...new Set(library.mocks.map(mock=>mock.year))].sort((a,b)=>b-a),selectedYear=year==='all'?'all' as const:Number(year);
  const attempts=progress.attempts.filter(attempt=>attempt.status==='completed'&&library.mocks.some(mock=>mock.id===attempt.mockId)&&(selectedYear==='all'||mockYearForAttempt(attempt,library)===selectedYear));
  const scores=attempts.map(attempt=>scoreAttempt(library.mocks.find(mock=>mock.id===attempt.mockId)!,attempt).percentage);
  const answered=attempts.reduce((sum,attempt)=>sum+Object.keys(attempt.answers).length,0),correct=attempts.reduce((sum,attempt)=>sum+scoreAttempt(library.mocks.find(mock=>mock.id===attempt.mockId)!,attempt).correct,0);
  const weak=weakQuestions(progress,library,'unresolved'),flags=progress.persistentFlags,conf=attempts.flatMap(attempt=>Object.values(attempt.confidence));
  const averageSeconds=answered?attempts.reduce((sum,attempt)=>sum+attempt.elapsedSeconds,0)/answered:0;
  const mapped=new Map<string,{correct:number;answered:number}>();for(const attempt of attempts){const mock=library.mocks.find(item=>item.id===attempt.mockId)!;for(const question of mock.questions){if(attempt.answers[question.id]===undefined||!['high','medium'].includes(question.mappingConfidence))continue;const key=question.officialModuleId||question.topic,row=mapped.get(key)??{correct:0,answered:0};row.answered++;if(attempt.answers[question.id]===question.correctChoiceIndex)row.correct++;mapped.set(key,row)}}
  const filtered=sortMocks(filterMocksByYear(library.mocks,selectedYear).filter(mock=>(provider==='all'||mock.provider===provider)&&(status==='all'||(status==='completed'&&latestAttempt(progress,mock.id)?.status==='completed')||(status==='not-started'&&!latestAttempt(progress,mock.id)))));
  return <><h1>Mock Exams</h1><p className="muted mt-2">Private, local-only exam practice. Source content is never bundled into public builds.</p>
    <div className="stats-grid mt-5">{[[filtered.length,'Mocks available'],[new Set(attempts.map(attempt=>attempt.mockId)).size,'Mocks completed'],[scores.length?`${(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1)}%`:'—','Average score'],[scores.length?`${Math.max(...scores).toFixed(1)}%`:'—','Best score'],[answered,'Questions attempted'],[answered?`${(correct/answered*100).toFixed(1)}%`:'—','Overall accuracy'],[weak.length,'Incorrect remaining'],[flags.length,'Flagged questions'],[conf.length?(attempts.reduce((sum,attempt)=>sum+averageConfidence(attempt),0)/attempts.length).toFixed(2):'—','Average confidence']].map(([value,label])=><div className="stat-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <section className="card mt-6"><h2>Performance {selectedYear==='all'?'— all years':`— ${selectedYear}`}</h2><p className="mt-3">Average time per answered question: <strong>{averageSeconds?`${averageSeconds.toFixed(1)}s`:'—'}</strong></p>{mapped.size?<ul className="mt-3 space-y-1">{[...mapped].map(([name,row])=><li key={name}>{name}: <strong>{(row.correct/row.answered*100).toFixed(1)}%</strong> ({row.correct}/{row.answered})</li>)}</ul>:<p className="muted mt-3">Topic and official-module performance appears after reliably mapped questions are attempted.</p>}</section>
    <section className="card mt-6"><h2>Incorrect Answers</h2><p className="muted mt-2">History is retained even after later correct answers.</p><div className="mt-4 flex flex-wrap gap-2"><Link className="btn btn-primary" to="/mocks/practice?filter=all">Practice all weak questions</Link><Link className="btn" to="/mocks/practice?filter=unresolved">Retry unresolved</Link><Link className="btn" to="/mocks/practice?filter=repeated">Incorrect more than once</Link></div><h2 className="mt-6">Flagged Questions</h2><p className="muted mt-2">{flags.length} persistent flags across all mock attempts.</p><Link className="btn mt-4" to="/mocks/practice?flags=1">Practice flagged questions</Link></section>
    <section className="card mt-6"><h2>Filter mocks</h2><div className="mt-3 grid gap-3 md:grid-cols-3"><label>Year<select value={year} onChange={event=>setYear(event.target.value)}><option value="all">All</option>{years.map(value=><option key={value}>{value}</option>)}</select></label><label>Provider<select value={provider} onChange={event=>setProvider(event.target.value)}><option value="all">All providers</option>{[...new Set(library.mocks.map(mock=>mock.provider))].map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}><option value="all">All</option><option value="completed">Completed</option><option value="not-started">Not started</option></select></label></div></section>
    <div className="mt-6 grid gap-5 lg:grid-cols-2">{filtered.map(mock=>{const attempt=latestAttempt(progress,mock.id),score=attempt?.status==='completed'?scoreAttempt(mock,attempt):null;return <article className="card" key={mock.id}><p className="eyebrow">{mock.provider} · {mock.year}</p><h2 className="mt-2">{mock.title}</h2><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div><dt>Questions</dt><dd>{mock.questionCount}</dd></div><div><dt>Time limit</dt><dd>{mock.timeLimitMinutes} min{mock.timeLimitProvenance&&<span className="block muted">Defaulted</span>}</dd></div><div><dt>Status</dt><dd>{!attempt?'Not Started':attempt.status==='completed'?'Completed':'In Progress'}</dd></div><div><dt>Previous score</dt><dd>{score?`${score.percentage}%`:'—'}</dd></div><div><dt>Answered</dt><dd>{attempt?Object.keys(attempt.answers).length:0}</dd></div><div><dt>Last attempted</dt><dd>{attempt?new Date(attempt.updatedAt).toLocaleDateString():'—'}</dd></div></dl><div className="mt-5 flex flex-wrap gap-2"><Link className="btn btn-primary" to={`/mocks/${mock.id}`}>{attempt?.status==='in-progress'?'Continue':attempt?.status==='completed'?'Retry':'Start'}</Link><Link className="btn" to={`/mocks/${mock.id}?mode=practice`}>Practice mode</Link>{attempt?.status==='completed'&&<Link className="btn" to={`/mocks/${mock.id}/review`}>Review</Link>}</div></article>})}</div></>;
}
