import {Link,useParams} from 'react-router-dom';
import {getTopic} from '../content/curriculum';
import {lessons} from '../content/lessonManifest';
import {completedOfficialQuantModules} from '../content/quantitativeCurriculum';
import {officialEconomicsModules,officialEconomicsModuleCount,verifiedOfficialEconomicsModules} from '../content/economicsCurriculum';
import {officialFsaModules,officialFsaModuleCount,verifiedOfficialFsaModules} from '../content/fsaCurriculum';
import {officialCorporateIssuersModules,officialCorporateIssuersModuleCount,verifiedOfficialCorporateIssuersModules} from '../content/corporateIssuersCurriculum';
import {useProgress} from '../hooks/useProgress';
import {useContentStats} from '../hooks/useContentStats';
import {quizScore} from '../services/progressService';
import {NotFoundPage} from './NotFoundPage';

export function TopicPage(){
 const{id}=useParams(),topic=id?getTopic(id):undefined,{progress}=useProgress(),stats=useContentStats();if(!topic)return <NotFoundPage/>;
 const available=lessons.filter(lesson=>lesson.topicId===topic.id),scores=available.map(lesson=>{const attempts=progress.quizAttempts.filter(attempt=>attempt.lessonId===lesson.id);return{lesson,attempts:attempts.length,score:quizScore(attempts)}}).filter(item=>item.attempts>0).sort((a,b)=>b.score-a.score),strong=scores.slice(0,3),weak=[...scores].reverse().slice(0,3),recommended=weak.length?weak:available.filter(lesson=>!progress.completedLessons.includes(lesson.id)).slice(0,3).map(lesson=>({lesson,attempts:0,score:0}));
 return <><p className="eyebrow">Level I topic</p><h1>{topic.title}</h1><p className="muted mt-2">{topic.description}</p>
 {topic.id==='quantitative-methods'&&<section className="card mt-6"><h2>Official CFA 2027 Quantitative Methods</h2><p className="mt-2 text-2xl font-bold">11 official modules · 12 study lessons</p><p className="muted mt-1">Official LM7 is presented as LM7A — Estimation and LM7B — Hypothesis Testing; both study lessons are required for one official-module completion.</p>
 <div className="stats-grid mt-4"><div className="stat-card"><strong>{stats.loading?'…':stats.officialQuantQuestions}</strong><span>Official questions</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialQuantFlashcards}</strong><span>Official flashcards</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialQuantFormulas}</strong><span>Official formulas</span></div><div className="stat-card"><strong>{quizScore(progress.quizAttempts)}%</strong><span>Average quiz score</span></div></div>
 <p className="mt-4">{completedOfficialQuantModules(progress.completedLessons).length}/11 official modules completed · {progress.completedLessons.filter(item=>available.some(lesson=>lesson.id===item)).length}/12 study lessons completed.</p><p className="muted mt-1">Supplementary sections are identified separately and excluded from official totals and default assessments.</p>
 <div className="mt-4 grid gap-4 md:grid-cols-3"><div><h3>Strongest modules</h3><p className="muted text-sm">{strong.length?strong.map(x=>`${x.lesson.title} (${x.score}%)`).join(', '):'Complete practice to calculate.'}</p></div><div><h3>Weakest modules</h3><p className="muted text-sm">{weak.length?weak.map(x=>`${x.lesson.title} (${x.score}%)`).join(', '):'Complete practice to calculate.'}</p></div><div><h3>Recommended review</h3><p className="muted text-sm">{recommended.map(x=>x.lesson.title).join(', ')||'Review completed modules.'}</p></div></div>
 <div className="mt-5 flex flex-wrap gap-2"><Link className="btn btn-primary" to="/practice?mode=quantitative">Start comprehensive practice</Link><Link className="btn" to="/flashcards">Start Quantitative flashcards</Link><Link className="btn" to="/formulas">Open Quantitative formula sheet</Link></div></section>}
 {topic.id==='economics'&&<section className="card mt-6"><h2>Official CFA 2027 Economics</h2><p className="mt-2 text-2xl font-bold">{verifiedOfficialEconomicsModules.length} / {officialEconomicsModuleCount} official modules published</p><p className="muted mt-1">Each verified module is produced and content-verified against the official 2027 curriculum before publication; unpublished modules remain mapping-only.</p>
 <div className="stats-grid mt-4"><div className="stat-card"><strong>{stats.loading?'…':stats.officialEconomicsQuestions}</strong><span>Official questions</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialEconomicsFlashcards}</strong><span>Official flashcards</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialEconomicsFormulas}</strong><span>Official formulas</span></div></div>
 <ul className="mt-4 grid gap-2 sm:grid-cols-2">{officialEconomicsModules.map(module=><li key={module.id} className="flex items-center justify-between gap-2"><span>{module.id} — {module.title}</span><span className={`badge ${module.status==='verified'?'':'opacity-70'}`}>{module.status==='verified'?'Verified':'Coming soon'}</span></li>)}</ul>
 <div className="mt-5 flex flex-wrap gap-2"><Link className="btn btn-primary" to="/practice?mode=economics">Start Economics comprehensive assessment</Link><Link className="btn" to="/flashcards">Start Economics flashcards</Link><Link className="btn" to="/formulas">Open Economics formula sheet</Link></div>
 </section>}
 {topic.id==='financial-statement-analysis'&&<section className="card mt-6"><h2>Official CFA 2027 Financial Statement Analysis</h2><p className="mt-2 text-2xl font-bold">{verifiedOfficialFsaModules.length} / {officialFsaModuleCount} official modules published</p><p className="muted mt-1">Each verified module is produced and content-verified against the official 2027 curriculum before publication; unpublished modules remain mapping-only.</p>
 <div className="stats-grid mt-4"><div className="stat-card"><strong>{stats.loading?'…':stats.officialFsaQuestions}</strong><span>Official questions</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialFsaFlashcards}</strong><span>Official flashcards</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialFsaFormulas}</strong><span>Official formulas</span></div></div>
 <ul className="mt-4 grid gap-2 sm:grid-cols-2">{officialFsaModules.map(module=><li key={module.id} className="flex items-center justify-between gap-2"><span>{module.id} — {module.title}</span><span className={`badge ${module.status==='verified'?'':'opacity-70'}`}>{module.status==='verified'?'Verified':'Coming soon'}</span></li>)}</ul>
 <div className="mt-5 flex flex-wrap gap-2"><Link className="btn btn-primary" to="/practice?lesson=fsa-01-introduction-to-financial-statement-analysis&mode=chapter-exam">Start FSA-LM1 chapter exam</Link><Link className="btn" to="/flashcards?lesson=fsa-01-introduction-to-financial-statement-analysis">Start FSA flashcards</Link><Link className="btn" to="/formulas">Open Formula Explorer</Link></div>
 </section>}
 {topic.id==='corporate-issuers'&&<section className="card mt-6"><h2>Official CFA 2027 Corporate Finance / Corporate Issuers</h2><p className="mt-2 text-2xl font-bold">{verifiedOfficialCorporateIssuersModules.length} / {officialCorporateIssuersModuleCount} official modules published · {Math.round(verifiedOfficialCorporateIssuersModules.length/officialCorporateIssuersModuleCount*100)}%</p><p className="muted mt-1">The official 2027 source labels the topic Corporate Finance; this application retains the established Corporate Issuers navigation label. Only verified modules are published.</p>
 <div className="stats-grid mt-4"><div className="stat-card"><strong>{stats.loading?'…':stats.officialCorporateIssuersQuestions}</strong><span>Official questions</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialCorporateIssuersFlashcards}</strong><span>Official flashcards</span></div><div className="stat-card"><strong>{stats.loading?'…':stats.officialCorporateIssuersFormulas}</strong><span>Official formulas</span></div></div>
 <ul className="mt-4 grid gap-2 sm:grid-cols-2">{officialCorporateIssuersModules.map(module=><li key={module.id} className="flex items-center justify-between gap-2"><span>{module.id} — {module.title}</span><span className={`badge ${module.status==='verified'?'':'opacity-70'}`}>{module.status==='verified'?'Verified':'Coming soon'}</span></li>)}</ul>
 <div className="mt-5 flex flex-wrap gap-2"><Link className="btn" to="/practice?lesson=corporate-issuers-01-organizational-forms-corporate-issuer-features-and-ownership&mode=chapter-exam">CI-LM1 exam</Link><Link className="btn" to="/practice?lesson=corporate-issuers-02-investors-and-other-stakeholders&mode=chapter-exam">CI-LM2 exam</Link><Link className="btn" to="/practice?lesson=corporate-issuers-03-corporate-governance-conflicts-mechanisms-risks-and-benefits&mode=chapter-exam">CI-LM3 exam</Link><Link className="btn" to="/practice?lesson=corporate-issuers-04-working-capital-and-liquidity&mode=chapter-exam">CI-LM4 exam</Link><Link className="btn" to="/practice?lesson=corporate-issuers-05-capital-investments-and-capital-allocation&mode=chapter-exam">CI-LM5 exam</Link><Link className="btn" to="/practice?lesson=corporate-issuers-06-capital-structure&mode=chapter-exam">CI-LM6 exam</Link><Link className="btn btn-primary" to="/practice?lesson=corporate-issuers-07-business-models&mode=chapter-exam">CI-LM7 exam</Link><Link className="btn" to="/flashcards?lesson=corporate-issuers-07-business-models">CI-LM7 cards</Link></div>
 </section>}
 <div className="mt-6 grid gap-3">{available.length?available.map(lesson=><Link className="card card-hover block" key={lesson.id} to={`/lessons/${lesson.id}`}><span className="badge">Study lesson {lesson.order}{lesson.subdivision?` · Official LM7${lesson.subdivision}`:''}</span><h2 className="mt-3">{lesson.title}</h2><p className="muted mt-2">{lesson.officialModuleTitle} · {lesson.estimatedMinutes} minutes · {lesson.difficulty}</p></Link>):<div className="card"><h2>Content pending</h2><p className="muted mt-2">No completed lessons are published for this topic yet.</p></div>}</div></>;
}
