import {useState} from 'react';
export type ESGScenario='flood'|'efficiency'|'turnover'|'supplier-labor'|'data-privacy'|'board-controls';
export const esgScenarios:Record<ESGScenario,{label:string;category:'Environmental'|'Social'|'Governance';classification:string;exposure:'Direct'|'Indirect';stakeholders:string;reasoning:string}>={
 flood:{label:'Flood threatens the issuer’s only plant',category:'Environmental',classification:'Physical risk',exposure:'Direct',stakeholders:'Employees, customers, lenders, shareholders',reasoning:'Asset exposure can produce downtime, repair costs, lost sales, and weaker debt coverage.'},
 efficiency:{label:'Energy-efficient equipment cuts input use',category:'Environmental',classification:'Opportunity',exposure:'Direct',stakeholders:'Customers, employees, capital providers',reasoning:'Lower resource use may reduce operating cost and transition exposure.'},
 turnover:{label:'Employee turnover disrupts production',category:'Social',classification:'Human-capital risk',exposure:'Direct',stakeholders:'Employees, customers, shareholders',reasoning:'Turnover can raise recruitment and training cost while reducing quality and output.'},
 'supplier-labor':{label:'Supplier labor controversy halts components',category:'Social',classification:'Value-chain risk',exposure:'Indirect',stakeholders:'Suppliers, workers, customers, investors',reasoning:'The issuer inherits disruption, switching costs, and reputation exposure through its supplier.'},
 'data-privacy':{label:'New privacy controls strengthen customer trust',category:'Social',classification:'Risk mitigation and opportunity',exposure:'Direct',stakeholders:'Customers, regulators, shareholders',reasoning:'Stronger data treatment can reduce failure exposure and support retention.'},
 'board-controls':{label:'Weak board expertise and internal controls',category:'Governance',classification:'Oversight risk',exposure:'Direct',stakeholders:'All capital providers and operating stakeholders',reasoning:'Weak oversight can impair risk identification and decision quality; detailed mechanisms belong to LM3.'}
};
export function ESGRiskOpportunityClassifier(){const[value,setValue]=useState<ESGScenario>('flood'),s=esgScenarios[value];return <section className="card" aria-labelledby="esg-classifier-title"><h2 id="esg-classifier-title">ESG Risk / Opportunity Classifier</h2><p className="muted mt-2">Trace issuer-specific exposure to business consequences. A label alone is not an investment conclusion.</p><label className="label mt-4 block">Issuer scenario<select aria-label="ESG issuer scenario" className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800" value={value} onChange={e=>setValue(e.target.value as ESGScenario)}>{Object.entries(esgScenarios).map(([v,x])=><option key={v} value={v}>{x.label}</option>)}</select></label><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt className="font-semibold">Category</dt><dd>{s.category}</dd></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt className="font-semibold">Classification</dt><dd>{s.classification}</dd></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt className="font-semibold">Exposure</dt><dd>{s.exposure}</dd></div><div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><dt className="font-semibold">Stakeholders</dt><dd>{s.stakeholders}</dd></div></dl><p className="mt-4 rounded-lg bg-blue-50 p-3 text-sm dark:bg-blue-950"><strong>Reasoning:</strong> {s.reasoning}</p></section>}
