
import {lazy,Suspense} from 'react';
const BenchmarkDiagram=lazy(()=>import('./BenchmarkDiagram').then(m=>({default:m.BenchmarkDiagram})));
const CashFlowTimeline=lazy(()=>import('./CashFlowTimeline').then(m=>({default:m.CashFlowTimeline})));
const CompoundingFrequencyExplorer=lazy(()=>import('./CompoundingFrequencyExplorer').then(m=>({default:m.CompoundingFrequencyExplorer})));
const TVMCalculator=lazy(()=>import('./TVMCalculator').then(m=>({default:m.TVMCalculator})));
const DescriptiveStatisticsCalculator=lazy(()=>import('./DescriptiveStatisticsCalculator').then(m=>({default:m.DescriptiveStatisticsCalculator})));
const DistributionShapeExplorer=lazy(()=>import('./DistributionShapeExplorer').then(m=>({default:m.DistributionShapeExplorer})));
const ProbabilityTreeExplorer=lazy(()=>import('./ProbabilityTreeExplorer').then(m=>({default:m.ProbabilityTreeExplorer})));
const TwoAssetPortfolioCalculator=lazy(()=>import('./TwoAssetPortfolioCalculator').then(m=>({default:m.TwoAssetPortfolioCalculator})));
const PortfolioAllocationExplorer=lazy(()=>import('./PortfolioAllocationExplorer'));
const DistributionExplorer=lazy(()=>import('./DistributionExplorer').then(m=>({default:m.DistributionExplorer})));
const ZScoreProbabilityCalculator=lazy(()=>import('./ZScoreProbabilityCalculator').then(m=>({default:m.ZScoreProbabilityCalculator})));
const BinomialProbabilityCalculator=lazy(()=>import('./BinomialProbabilityCalculator').then(m=>({default:m.BinomialProbabilityCalculator})));
const ConfidenceIntervalCalculator=lazy(()=>import('./ConfidenceIntervalCalculator').then(m=>({default:m.ConfidenceIntervalCalculator})));
const SamplingMethodExplorer=lazy(()=>import('./SamplingMethodExplorer').then(m=>({default:m.SamplingMethodExplorer})));
const HypothesisTestDecisionTool=lazy(()=>import('./HypothesisTestDecisionTool').then(m=>({default:m.HypothesisTestDecisionTool})));
const PValueExplorer=lazy(()=>import('./PValueExplorer').then(m=>({default:m.PValueExplorer})));
const ErrorTradeoffExplorer=lazy(()=>import('./ErrorTradeoffExplorer').then(m=>({default:m.ErrorTradeoffExplorer})));
const CorrelationScatterplotExplorer=lazy(()=>import('./CorrelationScatterplotExplorer').then(m=>({default:m.CorrelationScatterplotExplorer})));
const SimpleRegressionCalculator=lazy(()=>import('./SimpleRegressionCalculator').then(m=>({default:m.SimpleRegressionCalculator})));
const RegressionOutputInterpreter=lazy(()=>import('./RegressionOutputInterpreter').then(m=>({default:m.RegressionOutputInterpreter})));
const MonteCarloPortfolioSimulator=lazy(()=>import('./MonteCarloPortfolioSimulator').then(m=>({default:m.MonteCarloPortfolioSimulator})));
const BootstrapExplorer=lazy(()=>import('./BootstrapExplorer').then(m=>({default:m.BootstrapExplorer})));
const ScenarioSensitivityStressExplorer=lazy(()=>import('./ScenarioSensitivityStressExplorer').then(m=>({default:m.ScenarioSensitivityStressExplorer})));
const ConfusionMatrixExplorer=lazy(()=>import('./ConfusionMatrixExplorer').then(m=>({default:m.ConfusionMatrixExplorer})));
const BiasLeakageScenarioTrainer=lazy(()=>import('./BiasLeakageScenarioTrainer').then(m=>({default:m.BiasLeakageScenarioTrainer})));
const ModelEvaluationExplorer=lazy(()=>import('./ModelEvaluationExplorer').then(m=>({default:m.ModelEvaluationExplorer})));
const GenerativeAIRiskExplorer=lazy(()=>import('./GenerativeAIRiskExplorer').then(m=>({default:m.GenerativeAIRiskExplorer})));
const MarketStructureSupplyExplorer=lazy(()=>import('./MarketStructureSupplyExplorer').then(m=>({default:m.MarketStructureSupplyExplorer})));
const BreakevenShutdownExplorer=lazy(()=>import('./BreakevenShutdownExplorer').then(m=>({default:m.BreakevenShutdownExplorer})));
const ConcentrationMeasureExplorer=lazy(()=>import('./ConcentrationMeasureExplorer').then(m=>({default:m.ConcentrationMeasureExplorer})));
const BusinessCycleIndicatorTimeline=lazy(()=>import('./BusinessCycleIndicatorTimeline').then(m=>({default:m.BusinessCycleIndicatorTimeline})));
const CreditCycleExplorer=lazy(()=>import('./CreditCycleExplorer').then(m=>({default:m.CreditCycleExplorer})));
const FiscalMultiplierExplorer=lazy(()=>import('./FiscalMultiplierExplorer').then(m=>({default:m.FiscalMultiplierExplorer})));
const FiscalPolicyStanceComparator=lazy(()=>import('./FiscalPolicyStanceComparator').then(m=>({default:m.FiscalPolicyStanceComparator})));
const MonetaryTransmissionExplorer=lazy(()=>import('./MonetaryTransmissionExplorer').then(m=>({default:m.MonetaryTransmissionExplorer})));
const CentralBankTargetingComparator=lazy(()=>import('./CentralBankTargetingComparator').then(m=>({default:m.CentralBankTargetingComparator})));
const GeopoliticalRiskScenarioMap=lazy(()=>import('./GeopoliticalRiskScenarioMap').then(m=>({default:m.GeopoliticalRiskScenarioMap})));
const TradeRestrictionWelfareDiagram=lazy(()=>import('./TradeRestrictionWelfareDiagram').then(m=>({default:m.TradeRestrictionWelfareDiagram})));
const TradingBlocComparator=lazy(()=>import('./TradingBlocComparator').then(m=>({default:m.TradingBlocComparator})));
const FXQuoteAndRegimeExplorer=lazy(()=>import('./FXQuoteAndRegimeExplorer').then(m=>({default:m.FXQuoteAndRegimeExplorer})));
const CrossRateAndForwardRateCalculator=lazy(()=>import('./CrossRateAndForwardRateCalculator').then(m=>({default:m.CrossRateAndForwardRateCalculator})));
const loading=<p role="status" className="card mt-6">Loading learning toolsâ€¦</p>;
export function LessonInteractiveTools({lessonId}:{lessonId:string}){let tools=null;if(lessonId==='quant-benchmarking-03')tools=<BenchmarkDiagram/>;else if(lessonId==='economics-firm-market-01')tools=<><MarketStructureSupplyExplorer/><BreakevenShutdownExplorer/><ConcentrationMeasureExplorer/></>;else if(lessonId==='economics-02-understanding-business-cycles')tools=<><BusinessCycleIndicatorTimeline/><CreditCycleExplorer/></>;else if(lessonId==='economics-03-fiscal-policy')tools=<><FiscalMultiplierExplorer/><FiscalPolicyStanceComparator/></>;else if(lessonId==='economics-04-monetary-policy')tools=<><MonetaryTransmissionExplorer/><CentralBankTargetingComparator/></>;else if(lessonId==='economics-05-introduction-to-geopolitics')tools=<GeopoliticalRiskScenarioMap/>;else if(lessonId==='economics-06-international-trade')tools=<><TradeRestrictionWelfareDiagram/><TradingBlocComparator/></>;else if(lessonId==='economics-07-capital-flows-and-the-fx-market')tools=<FXQuoteAndRegimeExplorer/>;else if(lessonId==='economics-08-exchange-rate-calculations')tools=<CrossRateAndForwardRateCalculator/>;else if(lessonId==='quant-tvm-04')tools=<><TVMCalculator/><CashFlowTimeline/><CompoundingFrequencyExplorer/></>;else if(lessonId==='quant-statistics-05')tools=<><DistributionShapeExplorer/><DescriptiveStatisticsCalculator/></>;else if(lessonId==='quant-probability-06')tools=<><ProbabilityTreeExplorer/><DistributionExplorer/><ZScoreProbabilityCalculator/><BinomialProbabilityCalculator/></>;else if(lessonId==='quant-distributions-07')tools=<><TwoAssetPortfolioCalculator/><PortfolioAllocationExplorer/></>;else if(lessonId==='quant-sampling-08')tools=<><ConfidenceIntervalCalculator/><SamplingMethodExplorer/></>;else if(lessonId==='quant-hypothesis-09')tools=<><HypothesisTestDecisionTool/><PValueExplorer/><ErrorTradeoffExplorer/></>;else if(lessonId==='quant-regression-10')tools=<><CorrelationScatterplotExplorer/><SimpleRegressionCalculator/><RegressionOutputInterpreter/></>;else if(lessonId==='quant-simulation-11')tools=<><MonteCarloPortfolioSimulator/><BootstrapExplorer/><ScenarioSensitivityStressExplorer/></>;else if(lessonId==='quant-data-ai-12')tools=<><ConfusionMatrixExplorer/><BiasLeakageScenarioTrainer/><ModelEvaluationExplorer/><GenerativeAIRiskExplorer/></>;return tools?<Suspense fallback={loading}><div className="mt-6 space-y-6">{tools}</div></Suspense>:null}
