import {useState} from 'react';

export type ForecastInputs={sales:number;salesGrowth:number;cogsMargin:number;opexMargin:number;beginDebt:number;debtChange:number;interestRate:number;taxRate:number;dso:number;inventoryDays:number;payableDays:number;beginReceivables:number;beginInventory:number;beginPayables:number;beginPpe:number;capex:number;depreciation:number;beginRetainedEarnings:number;dividends:number;beginCash:number;otherAssets:number;otherLiabilities:number;contributedCapital:number};
export const defaultForecastInputs:ForecastInputs={sales:1000,salesGrowth:10,cogsMargin:60,opexMargin:20,beginDebt:300,debtChange:0,interestRate:5,taxRate:25,dso:36.5,inventoryDays:73,payableDays:45,beginReceivables:100,beginInventory:120,beginPayables:80,beginPpe:600,capex:80,depreciation:50,beginRetainedEarnings:400,dividends:40,beginCash:100,otherAssets:100,otherLiabilities:100,contributedCapital:140};
export function buildForecast(x:ForecastInputs){
 const revenue=x.sales*(1+x.salesGrowth/100),cogs=revenue*x.cogsMargin/100,opex=revenue*x.opexMargin/100,ebit=revenue-cogs-opex;
 const interest=x.beginDebt*x.interestRate/100,pretax=ebit-interest,tax=Math.max(0,pretax*x.taxRate/100),netIncome=pretax-tax;
 const receivables=x.dso*revenue/365,inventory=x.inventoryDays*cogs/365,payables=x.payableDays*cogs/365;
 const changeWorkingCapital=(receivables-x.beginReceivables)+(inventory-x.beginInventory)-(payables-x.beginPayables);
 const cfo=netIncome+x.depreciation-changeWorkingCapital,cfi=-x.capex,cff=x.debtChange-x.dividends,endingCash=x.beginCash+cfo+cfi+cff;
 const endingPpe=x.beginPpe+x.capex-x.depreciation,endingDebt=x.beginDebt+x.debtChange,retainedEarnings=x.beginRetainedEarnings+netIncome-x.dividends;
 const assets=endingCash+receivables+inventory+endingPpe+x.otherAssets,liabilitiesAndEquity=payables+endingDebt+x.otherLiabilities+x.contributedCapital+retainedEarnings;
 return{revenue,cogs,opex,ebit,interest,pretax,tax,netIncome,receivables,inventory,payables,changeWorkingCapital,cfo,cfi,cff,endingCash,endingPpe,endingDebt,retainedEarnings,assets,liabilitiesAndEquity,balanceCheck:assets-liabilitiesAndEquity};
}
const money=(n:number)=>n.toFixed(1);
export function LinkedFinancialStatementForecastBuilder(){const[x,setX]=useState(defaultForecastInputs),r=buildForecast(x);const field=(key:keyof ForecastInputs,label:string)=><label className="label">{label}<input className="input mt-1" type="number" step="0.1" value={x[key]} onChange={e=>setX({...x,[key]:Number(e.target.value)})}/></label>;
 return <section className="card" aria-labelledby="linked-forecast-title"><h3 id="linked-forecast-title">Linked Financial Statement Forecast Builder</h3><p className="muted mt-2">Uses beginning-debt interest and a 365-day convention. Change assumptions and trace the deterministic three-statement links.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{field('sales','Current sales')}{field('salesGrowth','Sales growth %')}{field('cogsMargin','COGS / sales %')}{field('opexMargin','Operating expense / sales %')}{field('beginDebt','Beginning debt')}{field('debtChange','Debt issued/(repaid)')}{field('interestRate','Interest rate %')}{field('taxRate','Tax rate %')}{field('dso','DSO')}{field('inventoryDays','Inventory days')}{field('payableDays','Payable days')}{field('capex','Capex')}{field('depreciation','D&A')}{field('dividends','Dividends')}</div>
 <div className="mt-5 grid gap-4 md:grid-cols-3"><div><h4>Income statement</h4><p>Revenue: {money(r.revenue)}</p><p>EBIT: {money(r.ebit)}</p><p>Interest: {money(r.interest)}</p><p>Tax: {money(r.tax)}</p><p>Net income: {money(r.netIncome)}</p></div><div><h4>Cash flow</h4><p>CFO: {money(r.cfo)}</p><p>CFI: {money(r.cfi)}</p><p>CFF: {money(r.cff)}</p><p>Ending cash: {money(r.endingCash)}</p></div><div><h4>Closing balance sheet</h4><p>Receivables: {money(r.receivables)}</p><p>Inventory: {money(r.inventory)}</p><p>PP&amp;E: {money(r.endingPpe)}</p><p>Retained earnings: {money(r.retainedEarnings)}</p><p>Assets: {money(r.assets)}</p><p>Liabilities + equity: {money(r.liabilitiesAndEquity)}</p></div></div><p className={`mt-4 font-semibold ${Math.abs(r.balanceCheck)<0.05?'text-emerald-700':'text-amber-700'}`} role="status">Balance check (A − L − E): {money(r.balanceCheck)} {Math.abs(r.balanceCheck)<0.05?'— balanced':'— investigate missing or inconsistent links'}</p></section>}
