import{useMemo,useState}from'react';
export type ImpairmentInput={carryingAmount:number;fairValueLessCosts:number;valueInUse:number;undiscountedCashFlows:number;disposalProceeds:number};
export function evaluateLongLivedAsset(input:ImpairmentInput,framework:'ifrs'|'us-gaap'){
 const recoverableAmount=Math.max(input.fairValueLessCosts,input.valueInUse);
 const impaired=framework==='ifrs'?input.carryingAmount>recoverableAmount:input.carryingAmount>input.undiscountedCashFlows;
 const postImpairmentAmount=impaired?(framework==='ifrs'?recoverableAmount:input.fairValueLessCosts):input.carryingAmount;
 const impairmentLoss=Math.max(0,input.carryingAmount-postImpairmentAmount);
 return{recoverableAmount,impaired,impairmentLoss,postImpairmentAmount,disposalGainLoss:input.disposalProceeds-postImpairmentAmount,reversalPermitted:framework==='ifrs'};
}
export function LongLivedAssetImpairmentTrainer(){const[framework,setFramework]=useState<'ifrs'|'us-gaap'>('ifrs'),[carrying,setCarrying]=useState(18000),[proceeds,setProceeds]=useState(17000);const result=useMemo(()=>evaluateLongLivedAsset({carryingAmount:carrying,fairValueLessCosts:17000,valueInUse:16000,undiscountedCashFlows:19000,disposalProceeds:proceeds},framework),[framework,carrying,proceeds]);return <div className="card"><h3>Long-lived asset impairment and disposal trainer</h3><p className="muted mt-1 text-sm">Compare the IFRS one-step test with the US GAAP recoverability screen, then calculate derecognition.</p><label className="label mt-3 block" htmlFor="asset-framework">Framework</label><select id="asset-framework" value={framework} onChange={e=>setFramework(e.target.value as typeof framework)} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:bg-slate-800"><option value="ifrs">IFRS</option><option value="us-gaap">US GAAP</option></select><div className="mt-3 grid gap-3 sm:grid-cols-2"><label>Carrying amount<input aria-label="Carrying amount" type="number" value={carrying} onChange={e=>setCarrying(Number(e.target.value))}/></label><label>Disposal proceeds<input aria-label="Disposal proceeds" type="number" value={proceeds} onChange={e=>setProceeds(Number(e.target.value))}/></label></div><div className="mt-3" role="status"><p><strong>Impaired:</strong> {result.impaired?'Yes':'No'}</p><p><strong>Impairment loss:</strong> {result.impairmentLoss.toFixed(0)}</p><p><strong>Post-test carrying amount:</strong> {result.postImpairmentAmount.toFixed(0)}</p><p><strong>Disposal gain/(loss):</strong> {result.disposalGainLoss.toFixed(0)}</p><p className="muted text-sm">Reversal for an asset held for use is {result.reversalPermitted?'permitted under IFRS, subject to the no-impairment carrying-value ceiling':'prohibited under US GAAP'}.</p></div></div>}
