import{useMemo,useState}from'react';
export type InventoryMeasurementInput={cost:number;sellingPrice:number;completionCost:number;sellingCost:number;replacementCost?:number;normalProfitMargin?:number};
export function measureInventory(input:InventoryMeasurementInput,standard:'ifrs'|'us-non-lifo'|'us-lifo-retail'){
 const nrv=input.sellingPrice-input.completionCost-input.sellingCost;
 let comparison=nrv;
 if(standard==='us-lifo-retail'){const floor=nrv-(input.normalProfitMargin??0);comparison=Math.max(floor,Math.min(input.replacementCost??nrv,nrv))}
 const carryingAmount=Math.min(input.cost,comparison);return{nrv,comparison,carryingAmount,writeDown:Math.max(0,input.cost-carryingAmount),reversalPermitted:standard==='ifrs'};
}
export function LowerCostNrvTrainer(){const[cost,setCost]=useState(100),[price,setPrice]=useState(108),[standard,setStandard]=useState<'ifrs'|'us-non-lifo'|'us-lifo-retail'>('ifrs');const result=useMemo(()=>measureInventory({cost,sellingPrice:price,completionCost:8,sellingCost:6,replacementCost:88,normalProfitMargin:12},standard),[cost,price,standard]);return <div className="card"><h3>Lower-of-cost measurement trainer</h3><p className="muted mt-1 text-sm">Apply IFRS NRV, US GAAP non-LIFO NRV, or the US GAAP LIFO/retail market bounds.</p><label className="label mt-3 block" htmlFor="measurement-standard">Framework and method</label><select id="measurement-standard" className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:bg-slate-800" value={standard} onChange={e=>setStandard(e.target.value as typeof standard)}><option value="ifrs">IFRS</option><option value="us-non-lifo">US GAAP: non-LIFO/non-retail</option><option value="us-lifo-retail">US GAAP: LIFO or retail</option></select><div className="mt-3 grid gap-3 sm:grid-cols-2"><label>Cost<input aria-label="Inventory cost" type="number" value={cost} onChange={e=>setCost(Number(e.target.value))}/></label><label>Selling price<input aria-label="Selling price" type="number" value={price} onChange={e=>setPrice(Number(e.target.value))}/></label></div><div className="mt-3" role="status"><p><strong>NRV:</strong> {result.nrv.toFixed(2)}</p><p><strong>Comparison value:</strong> {result.comparison.toFixed(2)}</p><p><strong>Carrying amount:</strong> {result.carryingAmount.toFixed(2)}</p><p><strong>Write-down:</strong> {result.writeDown.toFixed(2)}</p><p className="muted text-sm">A later reversal is {result.reversalPermitted?'permitted up to the prior write-down under IFRS':'prohibited under US GAAP'}.</p></div></div>}
