import {useMemo,useState} from 'react';
import {simulatePortfolio} from '../../services/simulationService';

export function MonteCarloPortfolioSimulator(){
  const[initial,setInitial]=useState(100000),[drift,setDrift]=useState(.06),[vol,setVol]=useState(.15),[periods,setPeriods]=useState(10),[runs,setRuns]=useState(2000),[contribution,setContribution]=useState(0),[seed,setSeed]=useState(42);
  const result=useMemo(()=>simulatePortfolio({initialValue:initial,expectedReturn:drift,volatility:vol,periods,simulations:runs,contribution,seed}),[initial,drift,vol,periods,runs,contribution,seed]);
  const bins=useMemo(()=>{if('error'in result)return[];const min=Math.min(...result.terminalValues),max=Math.max(...result.terminalValues),counts=Array<number>(20).fill(0);for(const value of result.terminalValues)counts[Math.min(19,Math.floor((value-min)/(max-min||1)*20))]++;return counts},[result]);
  return <section className="card"><h2>Monte Carlo portfolio simulator</h2><div className="mt-3 grid grid-cols-2 gap-3 md:grid-cols-4">{([['Initial portfolio value',initial,setInitial],['Annual drift (decimal)',drift,setDrift],['Annual volatility (decimal)',vol,setVol],['Annual periods',periods,setPeriods],['Simulations',runs,setRuns],['End-of-period contribution',contribution,setContribution],['Random seed',seed,setSeed]] as [string,number,(n:number)=>void][]).map(([label,value,set])=><label className="label" key={label}>{label}<input type="number" value={value} onChange={event=>set(Number(event.target.value))}/></label>)}</div>{'error'in result?<p role="alert" className="mt-3 text-red-600">{result.error}</p>:<><svg role="img" aria-label="Histogram of simulated terminal portfolio values" viewBox="0 0 600 180" className="mt-4 w-full">{bins.map((count,index)=>{const height=count/Math.max(...bins)*150;return <rect key={index} x={index*30} y={170-height} width="27" height={height} fill="currentColor"/>})}</svg><p>Mean {result.mean.toFixed(2)} · Median {result.median.toFixed(2)} · 5th percentile {result.p5.toFixed(2)} · 95th percentile {result.p95.toFixed(2)} · Below initial {(result.probabilityBelowInitial*100).toFixed(1)}%</p></>}<p className="muted mt-2 text-xs">Illustrative geometric-Brownian-motion price paths with constant drift, volatility, independent annual draws, and contributions added after each return. More runs reduce sampling noise, not model risk.</p></section>;
}
