import {useState} from 'react';

export type OrganizationalForm='sole-proprietorship'|'general-partnership'|'limited-partnership'|'limited-company';
export const organizationalProfiles:Record<OrganizationalForm,{label:string;ownership:string;control:string;liability:string;continuity:string;capitalAccess:string;taxation:string;examSignal:string}>={
 'sole-proprietorship':{label:'Sole proprietorship',ownership:'One proprietor',control:'Direct owner control',liability:'Generally unlimited',continuity:'Closely tied to the owner',capitalAccess:'Owner resources and borrowing',taxation:'Usually owner-level; jurisdiction-specific',examSignal:'Maximum direct control paired with personal exposure'},
 'general-partnership':{label:'General partnership',ownership:'Two or more general partners',control:'Partners share operating authority',liability:'Generally unlimited for general partners',continuity:'Depends on agreement and partners',capitalAccess:'Partner resources and borrowing',taxation:'Often pass-through; jurisdiction-specific',examSignal:'Pooled skill and capital paired with shared exposure'},
 'limited-partnership':{label:'Limited partnership',ownership:'General and limited partners',control:'General partner operates; limited partners passive',liability:'GP generally unlimited; LP limited',continuity:'Depends on partnership agreement',capitalAccess:'General partner plus passive investor capital',taxation:'Often pass-through; jurisdiction-specific',examSignal:'Limited liability for the passive capital provider'},
 'limited-company':{label:'Limited company',ownership:'Shareholders',control:'Shareholders elect board; managers operate',liability:'Shareholders generally limited to investment',continuity:'Separate legal identity supports continuity',capitalAccess:'Transferable debt and equity claims',taxation:'May involve company and shareholder levels',examSignal:'Separate identity, divisible ownership, and scalable financing'}
};

export function OrganizationalFormComparator(){
 const[left,setLeft]=useState<OrganizationalForm>('sole-proprietorship'),[right,setRight]=useState<OrganizationalForm>('limited-company');
 const rows=[['Ownership','ownership'],['Operating control','control'],['Owner liability','liability'],['Continuity','continuity'],['Capital access','capitalAccess'],['Taxation','taxation']] as const;
 return <section className="card" aria-labelledby="organizational-form-comparator"><h2 id="organizational-form-comparator">Organizational Form Comparator</h2><p className="muted mt-2">Compare curriculum-level structural implications. Exact legal and tax treatment remains jurisdiction-specific.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="label">First form<select aria-label="First organizational form" className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800" value={left} onChange={event=>setLeft(event.target.value as OrganizationalForm)}>{Object.entries(organizationalProfiles).map(([value,profile])=><option key={value} value={value}>{profile.label}</option>)}</select></label><label className="label">Second form<select aria-label="Second organizational form" className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800" value={right} onChange={event=>setRight(event.target.value as OrganizationalForm)}>{Object.entries(organizationalProfiles).map(([value,profile])=><option key={value} value={value}>{profile.label}</option>)}</select></label></div><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Dimension</th><th className="p-2">{organizationalProfiles[left].label}</th><th className="p-2">{organizationalProfiles[right].label}</th></tr></thead><tbody>{rows.map(([label,key])=><tr key={key} className="border-t dark:border-slate-700"><th className="p-2">{label}</th><td className="p-2">{organizationalProfiles[left][key]}</td><td className="p-2">{organizationalProfiles[right][key]}</td></tr>)}</tbody></table></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><p className="rounded-lg bg-blue-50 p-3 text-sm dark:bg-blue-950"><strong>Exam signal:</strong> {organizationalProfiles[left].examSignal}</p><p className="rounded-lg bg-blue-50 p-3 text-sm dark:bg-blue-950"><strong>Exam signal:</strong> {organizationalProfiles[right].examSignal}</p></div></section>;
}
