import {useState} from 'react';

export type TransitionDirection='private-to-public'|'public-to-private';
export const transitionProfiles:Record<TransitionDirection,{label:string;benefits:string[];costs:string[];sequence:string[];conclusion:string}>={
 'private-to-public':{label:'Private → public',benefits:['Broader capital access','Greater investor liquidity','Observable market pricing','Tradable acquisition currency'],costs:['Recurring disclosure and compliance','Public scrutiny','Offering costs','Possible ownership and control dilution'],sequence:['Prepare and register the offering','Issue shares and obtain listing','Broaden ownership','Maintain recurring public disclosure'],conclusion:'The issuer exchanges privacy and concentrated control for capital-market access, liquidity, and price discovery.'},
 'public-to-private':{label:'Public → private',benefits:['More concentrated control','Potentially longer decision horizon','Reduced public-reporting burden','Less continuous market scrutiny'],costs:['Lower share liquidity','Less observable pricing','Narrower public-equity access','Financing required to acquire public float'],sequence:['Investor group proposes acquisition','Public shares are purchased','Shares are delisted','Ownership becomes concentrated'],conclusion:'The issuer exchanges public liquidity and broad capital access for concentrated control and reduced public-market obligations.'}
};

export function PublicPrivateTransitionMap(){const[direction,setDirection]=useState<TransitionDirection>('private-to-public'),profile=transitionProfiles[direction];return <section className="card" aria-labelledby="public-private-transition-map"><h2 id="public-private-transition-map">Public–Private Transition Map</h2><p className="muted mt-2">Trace the structural consequences of changing ownership status; this is an educational map, not a transaction recommendation.</p><label className="label mt-4 max-w-md">Transition<select aria-label="Ownership transition" className="mt-1 w-full rounded-lg border bg-white px-3 py-2 dark:border-slate-600 dark:bg-slate-800" value={direction} onChange={event=>setDirection(event.target.value as TransitionDirection)}><option value="private-to-public">Private to public</option><option value="public-to-private">Public to private</option></select></label><h3 className="mt-5">{profile.label}</h3><ol className="mt-3 grid gap-2 sm:grid-cols-4">{profile.sequence.map((step,index)=><li key={step} className="rounded-lg border p-3 text-sm dark:border-slate-700"><span className="badge">Step {index+1}</span><p className="mt-2">{step}</p></li>)}</ol><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><h3>Potential benefits</h3><ul className="mt-2 list-disc pl-5">{profile.benefits.map(item=><li key={item}>{item}</li>)}</ul></div><div><h3>Trade-offs</h3><ul className="mt-2 list-disc pl-5">{profile.costs.map(item=><li key={item}>{item}</li>)}</ul></div></div><p role="status" className="mt-4 rounded-lg bg-amber-50 p-3 text-sm dark:bg-amber-950"><strong>Interpretation:</strong> {profile.conclusion}</p></section>}
