

import type {Lesson} from '../data/types';
import {officialModuleForLesson,quantStudyLessonOrder} from './quantitativeCurriculum';
const lessonRecords:Lesson[]=[
{id:'quant-returns-01',topicId:'quantitative-methods',title:'Returns of Financial Assets and Instruments',filePath:'content/quantitative/01-returns.md',officialModuleTitle:'Rates and Returns',estimatedMinutes:45,difficulty:'Foundation',order:1,status:'available',questionSetId:'quantitative-returns',flashcardSetId:'quantitative-returns',formulaIds:['holding-period-return','price-return','income-return','exact-real-return','approximate-real-return','arithmetic-mean','geometric-mean','time-weighted-return','foreign-currency-return'],officialLearningOutcomes:['Calculate and interpret different return measures and their applications.','Compare money-weighted and time-weighted rates of return.','Calculate and interpret major return components and averages.']},
{id:'quant-returns-02',topicId:'quantitative-methods',title:'Types of Financial Returns',filePath:'content/quantitative/02-types-of-financial-returns.md',officialModuleTitle:'Rates and Returns',estimatedMinutes:55,difficulty:'Intermediate',order:2,status:'available',questionSetId:'quantitative-return-types',flashcardSetId:'quantitative-return-types',formulaIds:['simple-return-02','total-return-02','price-return-02','income-return-02','net-return-02','exact-real-return-02','approximate-real-return-02','leveraged-return-02','arithmetic-return-02','geometric-return-02','money-weighted-return-02','time-weighted-return-02','multi-period-return-02','annualized-return-02','foreign-currency-return-02','risk-premium-02','required-return-02'],officialLearningOutcomes:['Calculate and interpret major types of financial return.','Distinguish return measures by cash-flow treatment, compounding, inflation, fees, and currency perspective.','Compare money-weighted and time-weighted return and select an appropriate performance measure.']},
{id:'quant-benchmarking-03',topicId:'quantitative-methods',title:'Benchmarking Returns',filePath:'content/quantitative/03-benchmarking-returns.md',officialModuleTitle:'Rates and Returns',estimatedMinutes:50,difficulty:'Intermediate',order:3,status:'available',questionSetId:'quantitative-benchmarking',flashcardSetId:'quantitative-benchmarking',formulaIds:['tracking-difference-03','custom-benchmark-return-03','relative-return-03'],officialLearningOutcomes:['Explain the purposes and characteristics of investment benchmarks.','Distinguish strategic, tactical, absolute, relative, market, custom, and peer benchmarks.','Interpret tracking difference and explain benchmark selection, rebalancing, attribution, and limitations.']},
{id:'quant-tvm-04',topicId:'quantitative-methods',title:'Time Value of Money',filePath:'content/quantitative/04-time-value-of-money.md',officialModuleTitle:'Time Value of Money',estimatedMinutes:90,difficulty:'Intermediate',order:4,status:'available',questionSetId:'quantitative-tvm',flashcardSetId:'quantitative-tvm',formulaIds:['simple-interest-04','compound-fv-04','single-pv-04','discount-factor-04','ear-04','stated-rate-04','continuous-fv-04','continuous-pv-04','multiple-cf-pv-04','ordinary-annuity-pv-04','ordinary-annuity-fv-04','annuity-due-04','perpetuity-04','growing-perpetuity-04','growing-annuity-04','loan-payment-04','amortization-interest-04','bond-value-04','inflation-target-04'],officialLearningOutcomes:['Calculate and interpret present and future values for single and multiple cash flows.','Convert interest-rate conventions and value annuities, perpetuities, and growing cash flows.','Apply TVM to loans, bonds, investments, retirement planning, and inflation.']},
{id:'quant-statistics-05',topicId:'quantitative-methods',title:'Statistical Characteristics of Asset Returns',filePath:'content/quantitative/05-statistical-characteristics-of-asset-returns.md',officialModuleTitle:'Statistical Measures of Asset Returns',estimatedMinutes:75,difficulty:'Intermediate',order:5,status:'available',questionSetId:'quantitative-statistics',flashcardSetId:'quantitative-statistics',formulaIds:['arithmetic-mean-05','weighted-mean-05','geometric-mean-05','harmonic-mean-05','population-variance-05','sample-variance-05','population-standard-deviation-05','sample-standard-deviation-05','coefficient-variation-05','sharpe-ratio-05'],officialLearningOutcomes:['Calculate and interpret measures of central tendency and location for asset-return data.','Calculate and interpret measures of dispersion for populations and samples.','Interpret skewness, kurtosis, outliers, and limitations when describing return distributions.']},
{id:'quant-probability-06',topicId:'quantitative-methods',title:'Probability',filePath:'content/quantitative/06-probability.md',officialModuleTitle:'Probability Concepts',estimatedMinutes:85,difficulty:'Intermediate',order:6,status:'available',questionSetId:'quantitative-probability',flashcardSetId:'quantitative-probability',formulaIds:['complement-rule-06','addition-rule-06','multiplication-rule-06','conditional-probability-06','total-probability-06','bayes-rule-06','expected-value-06','random-variable-variance-06','covariance-06','correlation-06','portfolio-expected-return-06','two-asset-variance-06'],officialLearningOutcomes:['Explain and calculate unconditional, conditional, joint, and total probabilities.','Apply probability trees, Bayes formula, odds, expected value, and random-variable variance.','Calculate and interpret covariance, correlation, expected portfolio return, and two-asset portfolio variance.']},
{id:'quant-distributions-07',topicId:'quantitative-methods',title:'Common Probability Distributions',filePath:'content/quantitative/07-common-probability-distributions.md',officialModuleTitle:'Common Probability Distributions',estimatedMinutes:90,difficulty:'Intermediate',order:7,status:'available',questionSetId:'quantitative-distributions',flashcardSetId:'quantitative-distributions',formulaIds:['bernoulli-mean-07','bernoulli-variance-07','binomial-probability-07','binomial-mean-07','binomial-variance-07','continuous-uniform-mean-07','continuous-uniform-variance-07','z-score-07','reverse-standardization-07','normal-probability-07','lognormal-transform-07','student-t-statistic-07'],officialLearningOutcomes:['Distinguish and apply common discrete and continuous probability distributions.','Standardize normal variables and interpret normal and lognormal probabilities.','Explain Student\'s t distribution, degrees of freedom, distribution selection, and model limitations.']},
{id:'quant-sampling-08',topicId:'quantitative-methods',title:'Sampling and Estimation',filePath:'content/quantitative/08-sampling-and-estimation.md',officialModuleTitle:'Sampling and Estimation',estimatedMinutes:90,difficulty:'Intermediate',order:8,status:'available',questionSetId:'quantitative-sampling',flashcardSetId:'quantitative-sampling',formulaIds:['standard-error-08','z-confidence-interval-08','t-confidence-interval-08','margin-of-error-08','degrees-freedom-08'],officialLearningOutcomes:['Compare probability and non-probability sampling methods and sources of sampling error.','Explain sampling distributions, the Central Limit Theorem, standard error, and estimator properties.','Calculate and interpret confidence intervals for a population mean using Z or Student\'s t.']},
{"id":"quant-hypothesis-09","topicId":"quantitative-methods","title":"Hypothesis Testing","filePath":"content/quantitative/09-hypothesis-testing.md","officialModuleTitle":"Hypothesis Testing","estimatedMinutes":100,"difficulty":"Intermediate","order":9,"status":"available","questionSetId":"quantitative-hypothesis","flashcardSetId":"quantitative-hypothesis","formulaIds":["general-test-statistic-09","z-mean-test-09","t-mean-test-09","test-df-09","power-09","p-decision-09","ci-test-link-09"],"scopeStatements":["HT-01: Explain the purpose and structure of statistical hypothesis testing.","HT-02: Distinguish the null hypothesis from the alternative hypothesis.","HT-03: Distinguish one-tailed and two-tailed tests and select the appropriate form for a stated research question.","HT-04: Explain significance level, critical value, rejection region, test statistic, and p-value.","HT-05: Make a hypothesis-test decision using either the critical-value method or the p-value method.","HT-06: Explain Type I error, Type II error, and statistical power.","HT-07: Explain how significance level, sample size, effect size, and variability affect test power and error trade-offs.","HT-08: Distinguish statistical significance from economic or practical significance.","HT-09: Conduct and interpret a test of a population mean when population variance is known.","HT-10: Conduct and interpret a test of a population mean when population variance is unknown.","HT-11: Select appropriately between a Z-test and a Studentâ€™s t-test.","HT-12: Explain the role of degrees of freedom in a t-test.","HT-13: Explain the relationship between confidence intervals and two-sided hypothesis tests.","HT-14: Interpret failure to reject the null hypothesis correctly without claiming that the null has been proven true.","HT-15: Identify assumptions, limitations, and common errors in investment-related hypothesis testing."]},
{"id":"quant-regression-10","topicId":"quantitative-methods","title":"Applications of Simple Linear Regression in Finance","filePath":"content/quantitative/10-correlation-and-regression.md","officialModuleTitle":"Applications of Simple Linear Regression in Finance","estimatedMinutes":110,"difficulty":"Intermediate","order":10,"status":"available","questionSetId":"quantitative-regression","flashcardSetId":"quantitative-regression","formulaIds":["population-regression-10","regression-equation-10","slope-10","intercept-10","residual-10","sse-10","sst-10","ssr-10","r-squared-10","see-10","slope-se-10","slope-t-10","slope-ci-10","anova-mse-10","anova-f-10","prediction-leverage-10","prediction-interval-10","log-linear-10","linear-log-10","log-log-10","capm-regression-10"],"scopeStatements":["Describe and interpret simple linear regression and least-squares coefficient estimation.","Evaluate assumptions, residuals, goodness of fit, regression coefficients, and ANOVA results.","Calculate and interpret predictions, standard error of estimate, prediction intervals, and functional forms.","Calculate and interpret CAPM regression estimates."]},
{"id":"quant-simulation-11","topicId":"quantitative-methods","title":"Simulation Methods","filePath":"content/quantitative/11-simulation-methods.md","officialModuleTitle":"Simulation Methods","estimatedMinutes":110,"difficulty":"Intermediate","order":11,"status":"available","questionSetId":"quantitative-simulation","flashcardSetId":"quantitative-simulation","formulaIds":["simulated-mean-11","simulated-variance-11","simulation-se-11","simulation-percentile-11","bootstrap-se-11","bootstrap-ci-11","terminal-value-11"],"scopeStatements":["SM-01: Explain why simulation is useful when investment outcomes depend on uncertain inputs.","SM-02: Distinguish deterministic analysis, scenario analysis, sensitivity analysis, stress testing, historical simulation, bootstrapping, and Monte Carlo simulation.","SM-03: Describe the main steps in a Monte Carlo simulation.","SM-04: Explain the role of random variables, probability distributions, and repeated trials in simulation.","SM-05: Explain how sample size and number of iterations affect simulation precision.","SM-06: Interpret a simulated outcome distribution using its mean, dispersion, percentiles, and tail outcomes.","SM-07: Explain how correlation and dependence assumptions affect simulated portfolio outcomes.","SM-08: Explain the purpose and limitations of bootstrapping.","SM-09: Apply simulation concepts to portfolio return, risk, valuation, and planning problems.","SM-10: Identify model risk, input risk, distribution risk, correlation risk, and implementation risk.","SM-11: Explain the importance of reproducibility, random seeds, validation, and sensitivity checks.","SM-12: Evaluate the strengths and limitations of simulation-based investment analysis."]},
{"id":"quant-data-ai-12","topicId":"quantitative-methods","title":"Introduction to Financial Data Science","filePath":"content/quantitative/12-python-data-science-and-ai.md","officialModuleTitle":"Introduction to Financial Data Science","estimatedMinutes":120,"difficulty":"Intermediate","order":12,"status":"available","questionSetId":"quantitative-data-ai","flashcardSetId":"quantitative-data-ai","formulaIds":["accuracy-12","precision-12","recall-12","specificity-12","f1-12","false-positive-rate-12","true-positive-rate-12","linear-prediction-12","cv-average-12","prevalence-12"],"scopeStatements":["DAI-01: Describe how big data, machine learning, and artificial intelligence are used in financial data science, fintech, and investment management.","DAI-18: Supplementary model-evaluation metrics beyond verified official scope."]},
{"id":"economics-firm-market-01","topicId":"economics","title":"The Firm and Market Structures","filePath":"content/economics/01-firm-and-market-structures.md","officialModuleTitle":"The Firm and Market Structures","estimatedMinutes":105,"difficulty":"Intermediate","order":1,"status":"available","questionSetId":"economics-firm-market-01","flashcardSetId":"economics-firm-market-01","formulaIds":["economic-profit-eco-01","total-revenue-eco-01","average-costs-eco-01","unit-breakeven-eco-01","profit-max-output-eco-01","linear-demand-mr-eco-01","contribution-profit-eco-01","concentration-ratio-eco-01","hhi-eco-01","hhi-merger-change-eco-01"],"officialLearningOutcomes":["determine and interpret breakeven and shutdown points of production, as well as how economies and diseconomies of scale affect costs under perfect and imperfect competition","describe characteristics of perfect competition, monopolistic competition, oligopoly, and pure monopoly","explain supply and demand relationships under monopolistic competition, including the optimal price and output for firms as well as pricing strategy","explain supply and demand relationships under oligopoly, including the optimal price and output for firms as well as pricing strategy","identify the type of market structure within which a firm operates and describe the use and limitations of concentration measures"]},
{"id":"economics-02-understanding-business-cycles","topicId":"economics","title":"Understanding Business Cycles","filePath":"content/economics/02-understanding-business-cycles.md","officialModuleTitle":"Understanding Business Cycles","estimatedMinutes":90,"difficulty":"Intermediate","order":2,"status":"available","questionSetId":"economics-02-understanding-business-cycles","flashcardSetId":"economics-02-understanding-business-cycles","formulaIds":["output-gap-eco-02","diffusion-index-eco-02","inventory-sales-ratio-eco-02","credit-to-gdp-ratio-eco-02"],"officialLearningOutcomes":["describe the business cycle and its phases","describe credit cycles","describe how resource use, consumer and business activity, housing sector activity, and external trade sector activity vary over the business cycle and describe their measurement using economic indicators"]},
{"id":"economics-03-fiscal-policy","topicId":"economics","title":"Fiscal Policy","filePath":"content/economics/03-fiscal-policy.md","officialModuleTitle":"Fiscal Policy","estimatedMinutes":100,"difficulty":"Intermediate","order":3,"status":"available","questionSetId":"economics-03-fiscal-policy","flashcardSetId":"economics-03-fiscal-policy","formulaIds":["budget-balance-eco-03","disposable-income-eco-03","mpc-mps-identity-eco-03","simple-multiplier-eco-03","fiscal-multiplier-eco-03","balanced-budget-multiplier-eco-03","debt-to-gdp-ratio-eco-03"],"officialLearningOutcomes":["compare monetary and fiscal policy","describe roles and objectives of fiscal policy as well as arguments as to whether the size of a national debt relative to GDP matters","describe tools of fiscal policy, including their advantages and disadvantages","explain the implementation of fiscal policy and difficulties of implementation as well as whether a fiscal policy is expansionary or contractionary"]},
{"id":"economics-04-monetary-policy","topicId":"economics","title":"Monetary Policy","filePath":"content/economics/04-monetary-policy.md","officialModuleTitle":"Monetary Policy","estimatedMinutes":110,"difficulty":"Intermediate","order":4,"status":"available","questionSetId":"economics-04-monetary-policy","flashcardSetId":"economics-04-monetary-policy","formulaIds":["neutral-policy-rate-eco-04","policy-rate-gap-eco-04"],"officialLearningOutcomes":["describe the roles and objectives of central banks","describe tools used to implement monetary policy tools and the monetary transmission mechanism, and explain the relationships between monetary policy and economic growth, inflation, interest, and exchange rates","describe qualities of effective central banks; contrast their use of inflation, interest rate, and exchange rate targeting in expansionary or contractionary monetary policy; and describe the limitations of monetary policy","explain the interaction of monetary and fiscal policy"]},
{"id":"economics-05-introduction-to-geopolitics","topicId":"economics","title":"Introduction to Geopolitics","filePath":"content/economics/05-introduction-to-geopolitics.md","officialModuleTitle":"Introduction to Geopolitics","estimatedMinutes":100,"difficulty":"Intermediate","order":5,"status":"available","questionSetId":"economics-05-introduction-to-geopolitics","flashcardSetId":"economics-05-introduction-to-geopolitics","formulaIds":[],"officialLearningOutcomes":["describe geopolitics from a cooperation versus competition perspective","describe geopolitics and its relationship with globalization","describe functions and objectives of the international organizations that facilitate trade, including the World Bank, the International Monetary Fund, and the World Trade Organization","describe geopolitical risk","describe tools of geopolitics and their impact on regions and economies","describe the impact of geopolitical risk on investments"]},
{"id":"economics-06-international-trade","topicId":"economics","title":"International Trade","filePath":"content/economics/06-international-trade.md","officialModuleTitle":"International Trade","estimatedMinutes":100,"difficulty":"Intermediate","order":6,"status":"available","questionSetId":"economics-06-international-trade","flashcardSetId":"economics-06-international-trade","formulaIds":["cs-loss-tariff-quota-eco-06","ps-gain-tariff-quota-eco-06","revenue-or-rent-eco-06","deadweight-loss-eco-06"],"officialLearningOutcomes":["describe the benefits and costs of international trade","compare types of trade restrictions, such as tariffs, quotas, and export subsidies, and their economic implications","explain motivations for and advantages of trading blocs, common markets, and economic unions"]},
];
const officialOutcomes:Record<string,string[]>={
 'quant-returns-01':['describe, compare, and interpret returns','describe, compare, and interpret required rates of return, risk-free rates, risk premia, and inflation'],
 'quant-returns-02':['calculate, compare, and interpret different types of returns for financial assets, instruments, and indicators'],
 'quant-benchmarking-03':['calculate and compare money-weighted and time-weighted rates of return','describe choices and implications of weighting methods used in index construction and management, and calculate, interpret, and explain the value and return of an index'],
 'quant-tvm-04':['calculate and interpret the present value of fixed-income and equity instruments based on expected future cash flows','calculate and interpret an implied return for fixed-income instruments and required return and implied growth for equity instruments given present values and cash flows','explain cash flow additivity and no-arbitrage and use them to calculate implied forward rates, forward exchange rates, and option values'],
 'quant-statistics-05':['calculate and interpret measures of central tendency and location','calculate and interpret measures of dispersion','interpret skewness and kurtosis','calculate and interpret covariance and correlation','calculate and interpret semideviation and coefficient of variation'],
 'quant-probability-06':['calculate and interpret unconditional expected value, variance, and covariance','explain and interpret moments of key probability distributions','calculate and interpret conditional expectations, variances, and covariances','use Bayes formula to update probabilities'],
 'quant-sampling-08':['compare sampling methods and explain the central limit theorem','calculate and interpret point estimates and confidence intervals','evaluate estimator properties and sampling error'],
 'quant-hypothesis-09':['formulate and evaluate hypotheses','explain Type I and Type II errors, power, and statistical versus economic significance','select, calculate, and interpret appropriate hypothesis tests'],
 'quant-distributions-07':['calculate, interpret, and evaluate expected return, variance, standard deviation, covariance, and correlation of portfolio returns','describe, calculate, and interpret a minimum-variance portfolio and the efficient frontier','explain optimal portfolio selection using risk aversion and the capital allocation line, including its extension to the market portfolio and capital market line'],
 'quant-simulation-11':['explain and interpret historical simulation','explain and interpret bootstrap resampling','explain and interpret Monte Carlo simulation of financial asset prices and returns'],
 'quant-regression-10':['calculate and interpret an ordinary least-squares regression','evaluate regression assumptions, residuals, goodness of fit, and ANOVA','calculate and interpret predictions, standard error of estimate, prediction intervals, and functional forms','interpret CAPM regression estimates'],
 'quant-data-ai-12':['explain how big data, machine learning, and artificial intelligence are used in financial data science, fintech, and investment management'],
};
const manifestOverrides:Record<string,Partial<Lesson>>={
 'quant-benchmarking-03':{officialModuleTitle:'Benchmarking Returns'},
 'quant-tvm-04':{title:'The Time Value of Money in Finance',officialModuleTitle:'The Time Value of Money in Finance'},
 'quant-statistics-05':{officialModuleTitle:'Statistical Characteristics of Asset Returns'},
 'quant-probability-06':{title:'Statistical Distributions for Financial Asset Prices and Returns',officialModuleTitle:'Statistical Distributions for Financial Asset Prices and Returns',formulaIds:['complement-rule-06','addition-rule-06','multiplication-rule-06','conditional-probability-06','total-probability-06','bayes-rule-06','expected-value-06','random-variable-variance-06','covariance-06','correlation-06','bernoulli-mean-07','bernoulli-variance-07','binomial-probability-07','binomial-mean-07','binomial-variance-07','poisson-probability-06','poisson-moments-06','continuous-uniform-mean-07','continuous-uniform-variance-07','z-score-07','reverse-standardization-07','normal-probability-07','lognormal-transform-07']},
 'quant-sampling-08':{title:'Estimation',officialModuleTitle:'Estimation and Hypothesis Testing',subdivision:'A'},
 'quant-hypothesis-09':{officialModuleTitle:'Estimation and Hypothesis Testing',subdivision:'B'},
 'quant-distributions-07':{title:'The Return and Risk of a Financial Portfolio',officialModuleTitle:'The Return and Risk of a Financial Portfolio',filePath:'content/quantitative/07-return-risk-financial-portfolio.md',estimatedMinutes:120,formulaIds:['portfolio-expected-return-08','portfolio-variance-08','two-asset-variance-08','portfolio-standard-deviation-08','covariance-08','correlation-08','minimum-variance-weight-08','cal-return-08','cal-risk-08','portfolio-utility-08']},
 'quant-simulation-11':{title:'Simulation of Financial Asset Prices and Returns',officialModuleTitle:'Simulation of Financial Asset Prices and Returns'},
 'quant-regression-10':{title:'Applications of Simple Linear Regression in Finance',officialModuleTitle:'Applications of Simple Linear Regression in Finance'},
 'quant-data-ai-12':{title:'Introduction to Financial Data Science',officialModuleTitle:'Introduction to Financial Data Science'},
};
const v164FormulaIds:Record<string,string[]>={
 'quant-returns-01':['required-return-components-01','continuous-return-01','leveraged-equity-return-01'],
 'quant-benchmarking-03':['price-weighted-index-03','equal-weighted-index-return-03','cap-weighted-index-return-03','float-adjusted-cap-03'],
 'quant-tvm-04':['implied-forward-rate-04','forward-fx-rate-04','implied-equity-growth-04','put-call-parity-04'],
 'quant-statistics-05':['sample-covariance-05','correlation-05','target-semideviation-05','skewness-05','excess-kurtosis-05'],
 'quant-sampling-08':['student-t-statistic-07']
};
export const lessons:Lesson[]=lessonRecords.map(lesson=>{const module=officialModuleForLesson(lesson.id);return module?{...lesson,...manifestOverrides[lesson.id],formulaIds:[...(manifestOverrides[lesson.id]?.formulaIds??lesson.formulaIds),...(v164FormulaIds[lesson.id]??[])],order:quantStudyLessonOrder.indexOf(lesson.id)+1,officialModuleId:module.id,officialLearningOutcomes:officialOutcomes[lesson.id]}:lesson;}).sort((a,b)=>a.topicId.localeCompare(b.topicId)||a.order-b.order);
export const getLesson=(id:string)=>lessons.find(l=>l.id===id);
