import{writeFileSync}from'node:fs';
const id='fsa-05-analyzing-statements-of-cash-flows-ii',topicId='financial-statement-analysis';
const los=['analyze and interpret both reported and common-size cash flow statements','calculate and interpret free cash flow to the firm, free cash flow to equity, and performance and coverage cash flow ratios'];
const A=[
['For a mature company, the most sustainable primary cash source is:','operating activities.','repeated debt issuance.','asset liquidation.','Mature firms ultimately must fund themselves from operations.'],
['A growth company has negative CFO because receivables and inventory are expanding. The BEST interpretation is:','potentially normal temporarily, but unsustainable indefinitely.','always evidence of fraud.','proof that growth creates value.','Growth investment can depress CFO, but operations must eventually generate cash.'],
['A company reports positive CFO only because payables increased sharply. An analyst should MOST likely:','question the persistence of CFO.','treat the increase as permanent profit.','classify it as CFI.','Stretching supplier payments is not indefinitely repeatable.'],
['The first step in cash-flow evaluation is to:','identify major sources and uses across CFO, CFI, and CFF.','calculate FCFE only.','ignore financing flows.','An overall source/use assessment precedes detailed drivers.'],
['Rising CFO driven by higher net income rather than working-capital releases is generally:','higher quality and more sustainable.','less informative.','necessarily noncash.','Earnings-driven cash generation is usually more repeatable.'],
['Large recurring CFI outflows can be favorable when they reflect:','value-creating productive investment.','unexplained cash leakage.','routine debt repayment.','Investment outflows can support future operating capacity.'],
['A mature firm with positive CFO, weak investment opportunities, and persistent cash accumulation should consider:','returning cash to capital providers.','forcing negative-NPV investment.','reclassifying cash as revenue.','Surplus cash without productive uses can be distributed.'],
['Negative CFF most likely reflects:','net repayment, dividends, or share repurchases.','customer collections.','inventory purchases.','Financing outflows return capital to lenders or owners.'],
['CFO that consistently trails net income while receivables grow faster than sales is a:','cash-conversion warning sign.','guarantee of improving liquidity.','financing inflow.','Accrual earnings are not converting into cash.'],
['Under the inflow/outflow common-size approach, cash received from customers is divided by:','total cash inflows.','net revenue.','ending cash.','Each inflow is expressed as a percentage of total inflows.'],
['Under the net-revenue common-size approach, CFO is divided by:','net revenue.','total assets.','total debt.','Revenue scaling supports comparisons across firms and periods.'],
['A common-size statement is most useful because it:','reduces scale differences and highlights composition.','eliminates accounting judgment.','replaces the reported cash flow statement.','Percentages enable structural comparisons.'],
['Customer receipts are 70% of total inflows this year versus 55% last year. All else equal, operations have become:','a more important cash source.','a smaller cash source.','impossible to interpret.','The inflow mix shifted toward customers.'],
['Capital expenditure is 18% of revenue versus 9% for peers. The analyst should FIRST determine whether:','the firm is investing for growth or replacing inefficient assets.','the percentage proves fraud.','capex belongs in CFO.','Context determines whether high investment intensity is favorable.'],
['CFO margin rises from 12% to 17%. This means:','more operating cash is generated per revenue dollar.','asset turnover necessarily rose.','debt necessarily fell.','CFO divided by revenue measures cash conversion of sales.'],
['When comparing IFRS reporters, common-size CFO may require normalization because:','interest and dividend classifications can differ.','IFRS prohibits CFO.','revenue is never reported.','Classification choices can shift cash among sections.'],
['A one-time asset sale dominates cash inflows. A common-size inflow analysis will:','make the unusual investing concentration visible.','treat it as recurring CFO.','remove it automatically.','The composition view highlights dependence on non-operating cash.'],
['CFO is positive, CFI is negative, and CFF is negative. For a mature firm this pattern is often:','healthy if operations fund investment and distributions.','necessarily insolvent.','proof of shrinking sales.','Operations can finance assets and return capital.'],
['CFO is negative, CFI positive from asset sales, and CFF positive from borrowing. The MOST concerning fact is:','operations rely on external funding and liquidation.','cash increased.','debt is classified as financing.','The funding pattern is not sustainable long term.'],
['A working-capital release boosts CFO during a sales contraction. The analyst should view the boost as:','potentially temporary.','permanent operating growth.','an investing return.','Shrinking receivables/inventory can release cash once, not indefinitely.'],
['Reported cash-flow analysis should examine financing drivers such as:','debt issuance/repayment and owner distributions.','gross margin only.','inventory costing only.','These transactions explain CFF.'],
['A company funds dividends by borrowing while CFO is persistently negative. This policy is:','unlikely to be sustainable.','automatically value creating.','an operating source.','Distributions ultimately require internally generated cash.'],
['The BEST cross-company comparison combines:','reported source/use analysis, common-size trends, and normalization.','ending cash alone.','net income alone.','Multiple views reveal scale, composition, and classification effects.']];
const B=[
['CFO is 80, after-tax interest 6, and fixed-capital investment 30. FCFF is:','56.','44.','104.','FCFF = CFO + after-tax interest − FCInv = 56.'],
['CFO is 80, fixed-capital investment 30, and net borrowing 5. FCFE is:','55.','45.','115.','FCFE = CFO − FCInv + net borrowing = 55.'],
['NI is 50, noncash charges 12, after-tax interest 5, FCInv 20, and WCInv 7. FCFF is:','40.','30.','54.','50 + 12 + 5 − 20 − 7 = 40.'],
['FCFF is cash available to:','debt and equity capital providers.','common shareholders only.','employees only.','FCFF is pre-distribution cash for all capital providers.'],
['FCFE is cash available to:','common shareholders after debt cash flows and reinvestment.','all debt holders before interest.','suppliers before operations.','FCFE incorporates net borrowing and belongs to common equity.'],
['When IFRS interest paid is classified in financing, FCFF from CFO generally:','does not add after-tax interest again.','must subtract interest twice.','equals revenue.','CFO has not been reduced by financing-classified interest.'],
['CFO 100 and revenue 500 produce cash flow to revenue of:','20%.','5%.','500%.','100 ÷ 500 = 20%.'],
['CFO 90 and average assets 600 produce cash return on assets of:','15%.','6.7%.','690%.','90 ÷ 600 = 15%.'],
['CFO 75 and average equity 300 produce cash return on equity of:','25%.','4%.','375%.','75 ÷ 300 = 25%.'],
['CFO 84 and operating income 70 produce cash to income of:','1.20.','0.83.','14.0.','84 ÷ 70 = 1.20.'],
['CFO 66, preferred dividends 6, and 20 shares produce cash flow per share of:','3.00.','3.30.','2.70.','(66 − 6) ÷ 20 = 3.00.'],
['CFO 120 and total debt 400 produce debt coverage of:','0.30.','3.33.','520.','120 ÷ 400 = 0.30.'],
['CFO 70, interest paid 10, and taxes paid 20 produce interest coverage of:','10.0.','7.0.','4.0.','(70 + 10 + 20) ÷ 10 = 10.0.'],
['CFO 90 and cash paid for long-term assets 60 produce reinvestment ratio of:','1.50.','0.67.','150.0.','90 ÷ 60 = 1.50.'],
['CFO 80 and long-term debt repayment 20 produce debt-payment coverage of:','4.0.','0.25.','100.0.','80 ÷ 20 = 4.0.'],
['CFO 75 and dividends paid 25 produce dividend-payment coverage of:','3.0.','0.33.','100.0.','75 ÷ 25 = 3.0.'],
['CFO 120 and investing/financing outflows 150 produce investing-and-financing coverage of:','0.80.','1.25.','270.','120 ÷ 150 = 0.80.'],
['Positive FCFE most directly indicates:','cash remains after capital investment and net debt cash flows.','the firm has no debt.','all cash must be distributed.','Positive FCFE is capacity, not a distribution requirement.'],
['If debt repayments exceed new borrowing, net borrowing is:','negative and reduces FCFE.','positive and increases FCFE.','irrelevant to FCFE.','Net debt repayment is a use of equity-available cash.'],
['A higher debt-coverage ratio generally indicates:','stronger ability to support debt from CFO.','greater leverage necessarily.','weaker cash generation.','More CFO per debt dollar improves coverage.'],
['The ratio most directly measuring CFO per sales dollar is:','cash flow to revenue.','cash return on equity.','debt payment.','Its denominator is net revenue.'],
['The ratio most directly measuring ability to fund long-lived assets internally is:','reinvestment ratio.','cash flow per share.','cash to income.','It compares CFO with cash paid for long-term assets.']];
const all=[...A,...B],qs=[],cards=[];
for(let n=0;n<45;n++){const l=n<23?0:1,[stem,correct,w1,w2,ex]=all[n],idx=n%3,choices=[w1,w2];choices.splice(idx,0,correct);const supp=(l===0?n>=18:n>=40);qs.push({id:`fsa-lm5-q-${String(n+1).padStart(3,'0')}`,lessonId:id,topicId,officialLearningOutcome:los[l],difficulty:n%4===0?'hard':'medium',estimatedSeconds:60+(n%3)*15,stem,choices,correctChoiceIndex:idx,explanation:ex,incorrectChoiceExplanations:choices.map((c,k)=>k===idx?`Correct: ${ex}`:`Incorrect: ${c} does not apply the relevant cash-flow analysis relationship.`),relatedFormulaIds:[],tags:['cash flow analysis',`LOS ${l+1}`],...(supp?{supplementary:true}:{})});cards.push({id:`fsa-lm5-fc-${String(n+1).padStart(3,'0')}`,lessonId:id,topicId,front:stem,back:`${correct} ${ex}`,officialLearningOutcome:los[l],tags:['cash flow analysis',`LOS ${l+1}`],...(supp?{supplementary:true}:{})})}
const F=[['common-size-inflow-fsa-05','Common-size cash inflow','Cash inflow line ÷ Total cash inflows'],['common-size-revenue-fsa-05','Revenue-scaled cash flow','Cash flow line ÷ Net revenue'],['fcff-ni-fsa-05','FCFF from net income','FCFF = NI + NCC + Int(1 − tax rate) − FCInv − WCInv'],['fcff-cfo-fsa-05','FCFF from CFO','FCFF = CFO + Int(1 − tax rate) − FCInv'],['fcfe-fsa-05','FCFE','FCFE = CFO − FCInv + Net borrowing'],['cash-flow-revenue-fsa-05','Cash flow to revenue','CFO ÷ Net revenue'],['cash-return-assets-fsa-05','Cash return on assets','CFO ÷ Average total assets'],['cash-return-equity-fsa-05','Cash return on equity','CFO ÷ Average shareholders’ equity'],['cash-to-income-fsa-05','Cash to income','CFO ÷ Operating income'],['cash-flow-share-fsa-05','Cash flow per share','(CFO − Preferred dividends) ÷ Common shares outstanding'],['debt-coverage-fsa-05','Debt coverage','CFO ÷ Total debt'],['interest-coverage-fsa-05','Cash interest coverage','(CFO + Interest paid + Taxes paid) ÷ Interest paid'],['reinvestment-fsa-05','Reinvestment ratio','CFO ÷ Cash paid for long-term assets'],['debt-payment-fsa-05','Debt payment coverage','CFO ÷ Cash paid for long-term debt repayment'],['dividend-payment-fsa-05','Dividend payment coverage','CFO ÷ Dividends paid'],['investing-financing-coverage-fsa-05','Investing and financing coverage','CFO ÷ Cash outflows for investing and financing activities']];
const formulas=F.map(([fid,name,expression],i)=>({id:fid,name,expression,meaning:'A source-defined cash-flow analysis measure used for comparison and interpretation.',variables:{CFO:'Cash flow from operating activities'},intuition:'Relates operating cash generation or free cash flow to its claimants, investment needs, or comparison base.',workedExample:i<5?'See the free-cash-flow worked examples in the lesson.':'Apply the stated numerator and denominator consistently across periods.',commonMistake:'Failing to normalize IFRS classification choices or reversing numerator and denominator.',relatedLessonId:id,relatedLearningOutcome:los[i<2?0:1],tags:['cash flow','analysis']}));
writeFileSync(`src/data/questions/${id}.json`,JSON.stringify(qs,null,2)+'\n');writeFileSync(`src/data/flashcards/${id}.json`,JSON.stringify(cards,null,2)+'\n');writeFileSync(`src/data/formulas/${id}.json`,JSON.stringify(formulas,null,2)+'\n');console.log({q:qs.length,official:qs.filter(x=>!x.supplementary).length,answers:[0,1,2].map(i=>qs.filter(x=>x.correctChoiceIndex===i).length),formulas:formulas.length});
