import{writeFileSync}from'node:fs';
const lessonId='fsa-06-analysis-of-inventories',topicId='financial-statement-analysis';
const los=['describe the measurement of inventory at the lower of cost and net realisable value and its implications for financial statements and ratios','calculate and explain how inflation and deflation of inventory costs affect the financial statements and ratios of companies that use different inventory valuation methods',"describe the presentation and disclosures relating to inventories and explain issues that analysts should consider when examining a company's inventory disclosures and other sources of information"];
const cases=[
['Under IFRS, inventory cost is 120 and NRV is 112. Carrying value is:','112.','120.','8.','Lower of cost and NRV gives 112.',0],
['NRV is best defined as estimated selling price less:','completion and selling costs.','normal profit only.','replacement cost only.','NRV deducts completion and selling costs.',0],
['An IFRS inventory write-down is later followed by an NRV recovery. The company should:','reverse up to the original write-down.','never reverse it.','record revenue above original cost.','IFRS requires a limited reversal.',0],
['US GAAP treatment of a previous inventory write-down is to:','prohibit reversal.','require full reversal.','permit reversal above original cost.','US GAAP prohibits reversal.',0],
['For US GAAP inventory not measured using LIFO or retail, the comparison is lower of cost and:','NRV.','unbounded replacement cost.','historical selling price.','Non-LIFO/non-retail inventory uses NRV.',0],
['For US GAAP LIFO inventory, market cannot exceed:','NRV.','cost.','NRV less normal profit.','NRV is the ceiling.',0],
['For US GAAP LIFO inventory, the market floor is:','NRV less normal profit margin.','replacement cost plus profit.','original cost.','The floor preserves a normal profit margin.',0],
['NRV is 90, normal profit is 12, and replacement cost is 70. Market is:','78.','70.','90.','Replacement cost is raised to the 78 floor.',0],
['Cost is 100 and bounded market is 92. The write-down is:','8.','92.','192.','Lower of cost or market gives an 8 loss.',0],
['An inventory write-down generally causes current assets and profit to:','decrease.','increase.','remain unchanged.','The loss lowers inventory and earnings.',0],
['Immediately after a write-down, inventory turnover may mechanically:','increase.','decrease only.','become revenue divided by inventory.','The average inventory denominator is reduced.',0],
['A write-down-driven increase in turnover should be interpreted as:','not necessarily operational improvement.','proof of faster sales.','higher liquidity.','Accounting reduction can cause the increase.',0],
['Inventory with cost 74 and NRV 81 is carried under IFRS at:','74.','81.','7.','The lower amount is cost.',0],
['IFRS NRV assessment is generally performed:','item by item or for similar related groups.','only for total corporate assets.','only when inventory is sold.','The grouping must preserve relevant similarity.',0],
['A write-down expense is generally recognized in:','profit or loss, often in COGS.','other comprehensive income only.','financing cash flow.','The inventory loss is an income-statement expense.',0],
['Goods available cost 1,000 and ending inventory 240 imply COGS of:','760.','1,240.','240.','COGS equals goods available less ending inventory.',1],
['Beginning inventory 180 and purchases 720 give goods available of:','900.','540.','720.','Add beginning inventory and purchases.',1],
['In rising prices, FIFO COGS relative to LIFO COGS is normally:','lower.','higher.','the same by definition.','FIFO expenses older lower costs.',1],
['In rising prices, FIFO ending inventory relative to LIFO ending inventory is normally:','higher.','lower.','zero.','FIFO leaves recent higher costs in inventory.',1],
['In rising prices, FIFO gross profit relative to LIFO gross profit is normally:','higher.','lower.','identical.','Lower FIFO COGS raises gross profit.',1],
['In falling prices, FIFO relative to LIFO normally reports:','higher COGS.','lower COGS.','zero COGS.','FIFO expenses older higher costs during deflation.',1],
['In falling prices, FIFO ending inventory is normally:','lower than LIFO inventory.','higher than LIFO inventory.','always equal to specific identification.','Recent lower costs remain under FIFO.',1],
['Weighted-average unit cost equals:','goods available cost divided by units available.','sales divided by ending units.','COGS divided by revenue.','It averages the cost pool across available units.',1],
['Three hundred units cost 3,600 in total. Weighted-average unit cost is:','12.','10.','1,080.','3,600 divided by 300 is 12.',1],
['Average cost is 12 and 180 units sell. Weighted-average COGS is:','2,160.','1,440.','15.','Multiply units sold by average cost.',1],
['LIFO is permitted under:','US GAAP but not IFRS.','IFRS but not US GAAP.','both frameworks without restriction.','IFRS does not permit LIFO.',1],
['A cost-flow assumption:','need not match physical movement.','must always match physical movement.','changes total units available.','It allocates cost, not necessarily physical units.',1],
['FIFO inventory 620 and LIFO inventory 530 imply a LIFO reserve of:','90.','1,150.','−90.','Reserve equals FIFO inventory less LIFO inventory.',1],
['LIFO COGS is 800 and the reserve increases by 18. Estimated FIFO COGS is:','782.','818.','800.','Subtract the reserve increase from LIFO COGS.',1],
['A falling LIFO reserve caused by selling more units than purchased may indicate:','LIFO liquidation.','NRV recovery under IFRS.','weighted averaging.','Old layers are being drawn down.',1],
['During rising prices, LIFO liquidation usually makes current gross profit:','temporarily higher.','permanently lower.','unaffected.','Old low costs enter COGS.',1],
['A LIFO reserve of 80 and tax rate of 25% imply an approximate FIFO equity increase of:','60.','20.','80.','After-tax reserve is 80 × 75%.',1],
['When input costs and quantities are stable, cost-method differences generally:','narrow.','must widen.','reverse every period.','Stable costs reduce layer differences.',1],
['The method that leaves recent purchase costs in ending inventory is:','FIFO.','LIFO.','specific identification only.','FIFO expenses the oldest costs first.',1],
['The method that sends recent purchase costs to COGS is:','LIFO.','FIFO.','straight-line.','LIFO expenses the latest costs first.',1],
['Inventory turnover is calculated as:','COGS divided by average inventory.','revenue divided by COGS.','ending inventory divided by days.','The activity ratio relates sales cost to average stock.',2],
['COGS of 900 and average inventory of 150 give turnover of:','6.0 times.','0.167 times.','750 times.','900 divided by 150 is 6.',2],
['Turnover of 5 implies days inventory, using 365 days, of:','73 days.','5 days.','1,825 days.','365 divided by 5 is 73.',2],
['Revenue 1,000 and COGS 700 give gross profit margin of:','30%.','70%.','42.9%.','Gross profit is 300, or 30% of revenue.',2],
['Finished goods rising far faster than sales most directly warrants concern about:','weak demand or obsolescence.','automatic production growth.','lower tax rates.','Unsold finished stock can signal demand trouble.',2],
['A sharp rise in raw materials may be favorable when it reflects:','planned production growth.','a LIFO reversal.','revenue recognition.','Composition needs operating context.',2],
['Inventory pledged as collateral most directly affects analysis of:','financial flexibility.','gross revenue recognition.','weighted-average arithmetic.','Pledged assets constrain financing choices.',2],
['Recurring inventory write-downs may indicate:','weak forecasting or purchasing controls.','guaranteed rising demand.','lower completion costs.','Repeated losses warrant process scrutiny.',2],
['For peer comparison, a LIFO reporter should most directly be normalized using:','the LIFO reserve and its change.','only revenue growth.','the dividend payout ratio.','The reserve adjusts inventory and COGS.',2],
['The inventory note should disclose the accounting policies used to:','measure inventory.','forecast share prices.','set interest rates.','Measurement policies are core inventory disclosures.',2],
['A lower days-in-inventory figure is favorable only after checking:','stockouts, write-downs, and method differences.','whether revenue is zero.','the dividend date.','Low days can reflect adverse causes.',2],
['The best inventory analysis combines statements and notes with:','MD&A, industry data, and operating context.','the auditor name alone.','share count alone.','External and management evidence explains movements.',2],
['A rise in turnover caused solely by lower average inventory after a write-down means efficiency:','has not necessarily improved.','has certainly doubled.','cannot ever be measured.','The denominator change is mechanical.',2],
['Comparing FIFO and LIFO gross margins without normalization during inflation will tend to make FIFO margin appear:','higher.','lower.','identical.','FIFO uses older lower costs in COGS.',2],
['The strongest warning of a margin boost from old cost layers is:','declining quantities and a falling LIFO reserve.','rising purchases and stable reserve.','an IFRS reversal disclosure.','Those facts point to a LIFO liquidation.',2]
];
const qs=[],cards=[];for(let n=0;n<cases.length;n++){const[stem,correct,w1,w2,ex,li]=cases[n],idx=n%3,choices=[w1,w2];choices.splice(idx,0,correct);const supplementary=n>=40;qs.push({id:`fsa-lm6-q-${String(n+1).padStart(3,'0')}`,lessonId,topicId,officialLearningOutcome:los[li],difficulty:n%5===0?'hard':'medium',estimatedSeconds:60+(n%3)*15,stem,choices,correctChoiceIndex:idx,explanation:ex,incorrectChoiceExplanations:choices.map((c,k)=>k===idx?`Correct: ${ex}`:`Incorrect: ${c} conflicts with the inventory measurement or analysis rule tested.`),relatedFormulaIds:[],tags:['inventory analysis',`LOS ${li+1}`],...(supplementary?{supplementary:true}:{})});cards.push({id:`fsa-lm6-fc-${String(n+1).padStart(3,'0')}`,lessonId,topicId,front:stem,back:`${correct} ${ex}`,officialLearningOutcome:los[li],tags:['inventory analysis',`LOS ${li+1}`],...(supplementary?{supplementary:true}:{})})}
const formulaRows=[
['nrv-fsa-06','Net realisable value','NRV = Estimated selling price − Completion costs − Selling costs',los[0]],
['market-bounds-fsa-06','US GAAP market bounds','Floor = NRV − Normal profit margin; Market = median(Floor, Replacement cost, NRV)',los[0]],
['goods-available-fsa-06','Cost of goods available','Beginning inventory + Purchases',los[1]],
['cogs-inventory-fsa-06','Cost of goods sold','COGS = Cost of goods available − Ending inventory',los[1]],
['weighted-average-fsa-06','Weighted-average unit cost','Cost of goods available ÷ Units available',los[1]],
['lifo-reserve-fsa-06','LIFO reserve conversion','Reserve = FIFO inventory − LIFO inventory; FIFO COGS = LIFO COGS − Change in reserve',los[1]],
['inventory-turnover-fsa-06','Inventory turnover and days','Turnover = COGS ÷ Average inventory; Days inventory = 365 ÷ Turnover',los[2]],
['gross-margin-fsa-06','Gross profit margin','(Revenue − COGS) ÷ Revenue',los[2]]];
const formulas=formulaRows.map(([id,name,expression,outcome])=>({id,name,expression,meaning:'A source-defined inventory measurement or analysis relationship.',variables:{COGS:'Cost of goods sold',NRV:'Net realisable value'},intuition:'Connects inventory cost allocation or carrying value with reported performance and comparison.',workedExample:'See the corresponding numbered worked example in the lesson.',commonMistake:'Applying a framework rule or cost-trend direction without first identifying the method and facts.',relatedLessonId:lessonId,relatedLearningOutcome:outcome,tags:['inventory','financial statement analysis']}));
writeFileSync(`src/data/questions/${lessonId}.json`,JSON.stringify(qs,null,2)+'\n');writeFileSync(`src/data/flashcards/${lessonId}.json`,JSON.stringify(cards,null,2)+'\n');writeFileSync(`src/data/formulas/${lessonId}.json`,JSON.stringify(formulas,null,2)+'\n');console.log({questions:qs.length,official:qs.filter(x=>!x.supplementary).length,answers:[0,1,2].map(i=>qs.filter(x=>x.correctChoiceIndex===i).length),formulas:formulas.length});
