import{writeFileSync}from'node:fs';
const lessonId='fsa-07-analysis-of-long-term-assets',topicId='financial-statement-analysis';
const los=['compare the financial reporting of the following types of intangible assets: purchased, internally developed, and acquired in a business combination','explain and evaluate how impairment and derecognition of property, plant, and equipment and intangible assets affect the financial statements and ratios','analyze and interpret financial statement disclosures regarding property, plant, and equipment and intangible assets'];
const C=[
['A separately purchased patent is initially measured at:','cost including directly attributable preparation costs.','management’s estimate of future revenue.','zero until it earns revenue.','Purchased intangibles are initially recognized at directly attributable cost.',0],
['Under IFRS, expenditures in the research phase are:','expensed as incurred.','always capitalized.','recorded as goodwill.','IFRS requires research expenditure to be expensed.',0],
['Under IFRS, development expenditure is capitalized:','prospectively after all recognition criteria are demonstrated.','from project inception once any criterion is met.','only after commercial sales begin.','Qualifying development costs are capitalized only from the recognition date.',0],
['US GAAP generally treats research and development costs by:','expensing them, subject to specified software exceptions.','capitalizing all development.','recording them in OCI.','General US GAAP treatment is expense, with software exceptions.',0],
['Software to be sold under US GAAP is capitalized after:','technological feasibility is established.','the first research meeting.','all customer cash is collected.','Technological feasibility is the relevant threshold.',0],
['An identifiable intangible acquired in a business combination is recognized at:','fair value separately from goodwill.','the acquiree’s zero book value.','the acquirer’s research cost.','Acquisition accounting recognizes identifiable intangibles at fair value.',0],
['Consideration is 900 and identifiable net assets are 760. Goodwill is:','140.','1,660.','760.','Goodwill is the residual 900 − 760.',0],
['A finite-life intangible is generally:','amortized and tested when impairment indicators exist.','never amortized or tested.','revalued through revenue monthly.','Finite-life assets are allocated over useful life and tested on indication.',0],
['An indefinite-life intangible is:','not amortized but tested at least annually for impairment.','amortized over exactly 40 years.','never reviewed.','Indefinite-life classification replaces amortization with annual testing.',0],
['Capitalizing rather than expensing a qualifying cost initially produces:','higher assets and profit.','lower assets and profit.','unchanged CFO under every classification.','Capitalization defers expense and records an asset.',0],
['Compared with capitalization, immediate expensing generally produces higher:','later-period profit after the initial period, all else equal.','initial-period assets.','initial-period CFO.','Expensing avoids later amortization or depreciation.',0],
['Internally generated brands are generally not recognized because:','their cost cannot be distinguished reliably from developing the business overall.','they lack any economic value.','all brands are financial assets.','Recognition and reliable-measurement constraints prevent capitalization.',0],
['Training expenditure related to a new patent is most likely:','expensed.','included in patent cost.','goodwill.','Training does not prepare the patent itself for intended use.',0],
['A development project meets IFRS criteria halfway through the year. Earlier expenditure is:','not reinstated as an asset.','retrospectively capitalized.','recorded as revenue.','Capitalization is prospective from the recognition date.',0],
['The useful life classification of an indefinite-life intangible should be:','reassessed each reporting period.','treated as literally infinite.','ignored after acquisition.','Indefinite means no foreseeable limit and requires reassessment.',0],
['Under IFRS, recoverable amount is the higher of value in use and:','fair value less costs of disposal.','undiscounted cash flows.','historical cost.','The higher of the two valuation bases is recoverable amount.',1],
['Carrying amount 100, value in use 82, and FVLCD 88 produce IFRS impairment of:','12.','18.','0.','Recoverable amount is 88; loss is 100 − 88.',1],
['The US GAAP recoverability screen for held-for-use PPE compares carrying amount with:','undiscounted expected cash flows.','value in use only.','replacement cost only.','US GAAP uses undiscounted cash flows as its first step.',1],
['A US GAAP asset passes the undiscounted-cash-flow screen. The impairment loss is:','zero.','carrying amount minus fair value.','undiscounted cash flows minus fair value.','Measurement occurs only after the recoverability screen fails.',1],
['After a failed US GAAP recoverability screen, loss is measured using:','fair value.','value in use.','original salvage value.','The asset is written down to fair value.',1],
['An impairment loss immediately lowers:','assets, profit, and equity.','debt and operating cash flow.','revenue and cash.','The non-cash loss lowers carrying amount and earnings.',1],
['In an indirect cash-flow statement, an impairment loss is generally:','added back to net income in CFO.','an investing cash outflow.','a financing inflow.','It reduced income without using cash.',1],
['IFRS reversal of a PPE impairment is limited to:','the carrying amount that would exist without the impairment.','original historical cost regardless of depreciation.','unlimited fair value.','The no-impairment carrying value is the ceiling.',1],
['US GAAP reversal of impairment for an asset held for use is:','prohibited.','required annually.','reported in OCI.','US GAAP does not reverse held-for-use impairment.',1],
['A held-for-sale long-lived asset ceases to be:','depreciated or amortized.','presented on the balance sheet.','tested for measurement loss.','Depreciation stops once held-for-sale criteria are met.',1],
['Sale proceeds are 70 and carrying amount is 62. Derecognition produces:','a gain of 8.','a loss of 8.','revenue of 70 with no asset removal.','Gain equals proceeds minus carrying amount.',1],
['On sale of equipment, the investing cash inflow equals:','total proceeds.','only the gain.','carrying amount.','The entire cash receipt is investing cash flow.',1],
['A disposal gain in the indirect CFO reconciliation is:','deducted from net income.','added to net income.','classified as depreciation.','The investing-related gain must be removed from CFO.',1],
['After an impairment, future depreciation is usually:','lower because the depreciable base is lower.','higher by the impairment amount.','unchanged by definition.','The new carrying amount establishes a lower expense base.',1],
['A post-impairment rise in asset turnover may be:','mechanical rather than operational.','proof of higher unit sales.','caused by higher asset carrying amount.','A smaller denominator can raise the ratio.',1],
['For held-for-sale measurement, the asset is carried at the lower of carrying amount and:','fair value less costs to sell.','undiscounted cash flows.','replacement cost plus margin.','Held-for-sale measurement uses FVLCTS.',1],
['A non-current asset impairment normally has what immediate current-ratio effect?','No direct effect.','Always increases it.','Always reduces current liabilities.','Neither current assets nor current liabilities changes directly.',1],
['Gross PPE 240 and accumulated depreciation 144 imply net PPE of:','96.','384.','144.','Net PPE is gross PPE less accumulated depreciation.',2],
['Gross depreciable PPE 240 and annual depreciation 12 imply useful life of:','20 years.','12 years.','252 years.','240 ÷ 12 is 20.',2],
['Accumulated depreciation 144 and annual depreciation 12 imply average age of:','12 years.','20 years.','8 years.','144 ÷ 12 is 12.',2],
['Net PPE 96 and annual depreciation 12 imply remaining life of:','8 years.','12 years.','20 years.','96 ÷ 12 is 8.',2],
['Accumulated depreciation 144 and gross PPE 240 imply life elapsed of:','60%.','40%.','166.7%.','144 ÷ 240 is 60%.',2],
['Revenue 500 and average net PPE 200 produce fixed-asset turnover of:','2.5 times.','0.4 times.','700 times.','500 ÷ 200 is 2.5.',2],
['Capex 66 and depreciation 50 produce a reinvestment ratio of:','1.32.','0.76.','116.','66 ÷ 50 is 1.32.',2],
['A high fixed-asset turnover may reflect:','old or impaired assets rather than superior efficiency.','only strong pricing power.','a larger asset denominator.','Accounting age and impairment can shrink the denominator.',2],
['A longer estimated useful life, all else equal, produces:','lower annual depreciation and higher current profit.','higher annual depreciation.','no statement effect.','The same depreciable base is spread over more periods.',2],
['The PPE note’s opening-to-closing reconciliation helps identify:','additions, disposals, depreciation, impairment, and currency effects.','only revenue recognition.','only dividends.','The roll-forward explains changes in carrying amount.',2],
['An impairment sensitivity disclosure is most useful for assessing:','how assumption changes could reduce recoverable amount.','the legal title to inventory.','cash dividend timing.','Growth and discount-rate sensitivity reveal headroom risk.',2],
['Capex exceeding depreciation necessarily means:','neither value creation nor capacity growth can be concluded without context.','the company created value.','all assets are new.','Replacement prices, mix, and maintenance versus expansion matter.',2],
['Land should ideally be excluded from estimated-life calculations because it is:','not depreciable.','always impaired.','an intangible asset.','Including non-depreciable land distorts life estimates.',2]
];
const qs=[],cards=[];for(let n=0;n<C.length;n++){const[stem,correct,w1,w2,ex,li]=C[n],idx=n%3,choices=[w1,w2];choices.splice(idx,0,correct);const supplementary=n>=35;qs.push({id:`fsa-lm7-q-${String(n+1).padStart(3,'0')}`,lessonId,topicId,officialLearningOutcome:los[li],difficulty:n%5===0?'hard':'medium',estimatedSeconds:60+(n%3)*15,stem,choices,correctChoiceIndex:idx,explanation:ex,incorrectChoiceExplanations:choices.map((c,k)=>k===idx?`Correct: ${ex}`:`Incorrect: ${c} does not follow the applicable long-term-asset rule or analytical relationship.`),relatedFormulaIds:[],tags:['long-term assets',`LOS ${li+1}`],...(supplementary?{supplementary:true}:{})});const prompts=['State the governing rule for','Explain the analytical implication of','Resolve this long-term-asset review point:'];cards.push({id:`fsa-lm7-fc-${String(n+1).padStart(3,'0')}`,lessonId,topicId,front:`${prompts[n%3]} ${stem.charAt(0).toLowerCase()+stem.slice(1)}`,back:`${correct} ${ex}`,officialLearningOutcome:los[li],tags:['long-term assets',`LOS ${li+1}`],...(supplementary?{supplementary:true}:{})})}
const F=[
['goodwill-fsa-07','Goodwill','Consideration − Fair value of identifiable net assets',0],['recoverable-amount-fsa-07','IFRS recoverable amount','max(Value in use, Fair value less costs of disposal)',1],['ifrs-impairment-fsa-07','IFRS impairment loss','max(0, Carrying amount − Recoverable amount)',1],['us-recoverability-fsa-07','US GAAP recoverability screen','Impaired if Carrying amount > Undiscounted expected cash flows',1],['us-impairment-fsa-07','US GAAP impairment loss','Carrying amount − Fair value, after failed screen',1],['disposal-gain-fsa-07','Disposal gain or loss','Proceeds − Carrying amount at disposal',1],['net-ppe-fsa-07','Net PPE','Gross PPE − Accumulated depreciation',2],['useful-life-fsa-07','Estimated useful life','Gross depreciable PPE ÷ Annual depreciation',2],['asset-age-fsa-07','Estimated average age','Accumulated depreciation ÷ Annual depreciation',2],['remaining-life-fsa-07','Estimated remaining life','Net depreciable PPE ÷ Annual depreciation',2],['life-elapsed-fsa-07','Percentage of life elapsed','Accumulated depreciation ÷ Gross depreciable PPE',2],['fixed-asset-turnover-fsa-07','Fixed-asset turnover','Revenue ÷ Average net PPE',2],['reinvestment-ratio-fsa-07','PPE reinvestment ratio','Capital expenditure ÷ Depreciation expense',2]];
const formulas=F.map(([id,name,expression,li])=>({id,name,expression,meaning:'A source-defined long-term-asset measurement or disclosure-analysis relationship.',variables:{PPE:'Property, plant, and equipment'},intuition:'Connects recognition, carrying amount, impairment, disposal, or asset-age disclosures to reported performance.',workedExample:'See the corresponding worked example in the LM7 lesson.',commonMistake:'Ignoring framework differences, non-depreciable land, mixed asset populations, or mechanical ratio effects.',relatedLessonId:lessonId,relatedLearningOutcome:los[li],tags:['long-term assets','FSA']}));
writeFileSync(`src/data/questions/${lessonId}.json`,JSON.stringify(qs,null,2)+'\n');writeFileSync(`src/data/flashcards/${lessonId}.json`,JSON.stringify(cards,null,2)+'\n');writeFileSync(`src/data/formulas/${lessonId}.json`,JSON.stringify(formulas,null,2)+'\n');console.log({questions:qs.length,official:qs.filter(x=>!x.supplementary).length,answers:[0,1,2].map(i=>qs.filter(x=>x.correctChoiceIndex===i).length),formulas:formulas.length});
