import {Link} from 'react-router-dom';import {useEffect,useMemo,useState} from 'react';import type {Confidence,Question} from '../../data/types';import {assessmentScore,confidenceBreakdown,moduleBreakdown,selectBalancedAssessment,type AssessmentAnswer} from '../../services/assessmentService';import {QuestionCard} from './QuestionCard';import {AnswerExplanation} from './AnswerExplanation';import {ConfidenceSelector} from './ConfidenceSelector';import {Button} from '../common/Button';
const KEY='cfa-pass-quant-assessment-v1',CURRENT='2027-v1.6.5';
// Default assessment configuration: /90 official-scope questions.
type Saved={ids:string[];index:number;answers:AssessmentAnswer[];remaining:number;paused:boolean;curriculumVersion?:string};
export function ComprehensiveAssessment({questions}:{questions:Question[]}){
 const initial=useMemo(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)??'null') as Saved|null;if(saved?.ids?.length===90)return saved}catch{localStorage.removeItem(KEY)}return{ids:selectBalancedAssessment(questions).map(q=>q.id),index:0,answers:[],remaining:135*60,paused:false,curriculumVersion:CURRENT}},[questions]);
 const legacy=initial.curriculumVersion!==CURRENT,[list]=useState(()=>initial.ids.map(id=>questions.find(q=>q.id===id)!).filter(Boolean)),[index,setIndex]=useState(initial.index),[answers,setAnswers]=useState(initial.answers),[remaining,setRemaining]=useState(initial.remaining),[paused,setPaused]=useState(initial.paused),[selected,setSelected]=useState<number|null>(null),[confidence,setConfidence]=useState<Confidence|null>(null);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({ids:list.map(q=>q.id),index,answers,remaining,paused,curriculumVersion:legacy?initial.curriculumVersion??'legacy-pre-v1.6.5':CURRENT}))},[answers,index,initial.curriculumVersion,legacy,list,paused,remaining]);
 useEffect(()=>{if(paused||index>=list.length)return;const timer=setInterval(()=>setRemaining(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer)},[paused,index,list.length]);
 const legacyNotice=legacy?<p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900" role="status">Legacy assessment — preserved under its original curriculum mapping. Former distribution answers are not reinterpreted as LM8 portfolio performance.</p>:null;
 if(index>=list.length){const modules=legacy?{'Legacy pre-v1.6.5 mapping':{answered:answers.length,correct:answers.filter(x=>x.correct).length}}:moduleBreakdown(answers),conf=confidenceBreakdown(answers);return <section className="card"><h2>Assessment complete</h2>{legacyNotice}<p className="mt-2 text-3xl font-bold">{(assessmentScore(answers)*100).toFixed(1)}%</p><h3 className="mt-4">Module breakdown</h3><ul>{Object.entries(modules).map(([id,x])=><li key={id}>{id}: {x.correct}/{x.answered}</li>)}</ul><h3 className="mt-4">Confidence breakdown</h3><ul>{Object.entries(conf).map(([id,x])=><li key={id}>{id}: {x.correct}/{x.answered}</li>)}</ul><h3 className="mt-4">Incorrect-answer review</h3><ul className="mt-2 space-y-1">{answers.filter(a=>!a.correct).map(a=>{const item=list.find(q=>q.id===a.questionId);return item?<li key={a.questionId}><Link className="text-blue-700 underline dark:text-blue-300" to={`/lessons/${item.lessonId}`}>{item.stem}</Link></li>:null})}</ul><Button className="mt-4" onClick={()=>{localStorage.removeItem(KEY);location.reload()}}>Start new assessment</Button></section>}
 const q=list[index],revealed=selected!==null;function next(){if(selected===null||!confidence)return;setAnswers(a=>[...a,{questionId:q.id,lessonId:q.lessonId,correct:selected===q.correctChoiceIndex,confidence}]);setIndex(i=>i+1);setSelected(null);setConfidence(null)}
 return <section className="card">{legacyNotice}<div className="flex flex-wrap justify-between gap-2"><strong>Quantitative comprehensive assessment · {index+1}/{list.length}</strong><span aria-live="polite">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</span><Button onClick={()=>setPaused(x=>!x)}>{paused?'Resume':'Pause'}</Button></div>{paused?<p role="status" className="mt-6 text-center">Assessment paused. Progress is saved on this device.</p>:<div className="mt-5"><QuestionCard question={q} selected={selected} onSelect={setSelected} revealed={revealed}/>{revealed&&<><AnswerExplanation question={q} selected={selected}/><ConfidenceSelector value={confidence} onChange={setConfidence}/><Button className="btn-primary mt-4" disabled={!confidence} onClick={next}>Next</Button></>}</div>}</section>
}
