import {Link} from 'react-router-dom';import {useEffect,useMemo,useState} from 'react';import type {Confidence,Question} from '../../data/types';import {assessmentScore,confidenceBreakdown,moduleBreakdown,selectBalancedAssessment,type AssessmentAnswer} from '../../services/assessmentService';import {officialEconomicsModules} from '../../content/economicsCurriculum';import {QuestionCard} from './QuestionCard';import {AnswerExplanation} from './AnswerExplanation';import {ConfidenceSelector} from './ConfidenceSelector';import {Button} from '../common/Button';
const KEY='cfa-pass-economics-assessment-v1',SEED=2708,COUNT=60,DURATION=90*60;
// Default assessment configuration: 60 official-scope questions balanced across all 8 official Economics modules.
type Saved={ids:string[];index:number;answers:AssessmentAnswer[];remaining:number;paused:boolean};
const moduleTitle=(id:string)=>officialEconomicsModules.find(module=>module.id===id)?.title??id;
export function EconomicsComprehensiveAssessment({questions}:{questions:Question[]}){
 const initial=useMemo(()=>{try{const saved=JSON.parse(localStorage.getItem(KEY)??'null') as Saved|null;if(saved?.ids?.length===COUNT)return saved}catch{localStorage.removeItem(KEY)}return{ids:selectBalancedAssessment(questions,COUNT,SEED).map(q=>q.id),index:0,answers:[],remaining:DURATION,paused:false}},[questions]);
 const[list,setList]=useState(()=>initial.ids.map(id=>questions.find(q=>q.id===id)!).filter(Boolean)),[index,setIndex]=useState(initial.index),[answers,setAnswers]=useState(initial.answers),[remaining,setRemaining]=useState(initial.remaining),[paused,setPaused]=useState(initial.paused),[selected,setSelected]=useState<number|null>(null),[confidence,setConfidence]=useState<Confidence|null>(null);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify({ids:list.map(q=>q.id),index,answers,remaining,paused}))},[answers,index,list,paused,remaining]);
 useEffect(()=>{if(paused||index>=list.length)return;const timer=setInterval(()=>setRemaining(x=>Math.max(0,x-1)),1000);return()=>clearInterval(timer)},[paused,index,list.length]);
 if(index>=list.length||remaining===0){
  const modules=moduleBreakdown(answers),conf=confidenceBreakdown(answers),wrong=answers.filter(a=>!a.correct).map(a=>list.find(q=>q.id===a.questionId)).filter(Boolean) as Question[];
  const outcomes=Object.fromEntries([...new Set(answers.map(a=>list.find(q=>q.id===a.questionId)?.officialLearningOutcome??'Unmapped'))].map(outcome=>{const subset=answers.filter(a=>(list.find(q=>q.id===a.questionId)?.officialLearningOutcome??'Unmapped')===outcome);return[outcome,{answered:subset.length,correct:subset.filter(a=>a.correct).length}]}));
  return <section className="card"><h2>Economics comprehensive assessment complete</h2><p className="mt-2 text-3xl font-bold">{(assessmentScore(answers)*100).toFixed(1)}%</p>
   <h3 className="mt-5">Module breakdown</h3><ul className="mt-2 space-y-1">{Object.entries(modules).map(([id,value])=><li key={id}><strong>{value.correct}/{value.answered}</strong> — {id} {moduleTitle(id)}</li>)}</ul>
   <h3 className="mt-5">Learning outcome breakdown</h3><ul className="mt-2 space-y-1">{Object.entries(outcomes).map(([name,value])=><li key={name}><strong>{value.correct}/{value.answered}</strong> — {name}</li>)}</ul>
   <h3 className="mt-5">Confidence breakdown</h3><ul>{Object.entries(conf).map(([name,value])=><li key={name}>{name}: {value.correct}/{value.answered}</li>)}</ul>
   <h3 className="mt-5">Incorrect-answer review</h3>{wrong.length?<ul className="mt-2 space-y-3">{wrong.map(q=><li key={q.id}><Link className="text-blue-700 underline dark:text-blue-300" to={`/lessons/${q.lessonId}`}>{q.stem}</Link>{q.relatedFormulaIds.map(id=><Link key={id} className="ml-2 text-blue-700 underline dark:text-blue-300" to={`/formulas#${id}`}>{id}</Link>)}</li>)}</ul>:<p className="muted mt-2">No incorrect answers.</p>}
   <div className="mt-5 flex flex-wrap gap-2">{wrong.length>0&&<Button className="btn-primary" onClick={()=>{setList(shuffle(wrong));setIndex(0);setAnswers([]);setRemaining(DURATION);setPaused(false)}}>Retry weak areas</Button>}<Button onClick={()=>{localStorage.removeItem(KEY);location.reload()}}>Start new assessment</Button></div>
  </section>;
 }
 const q=list[index],revealed=selected!==null;function next(){if(selected===null||!confidence)return;setAnswers(a=>[...a,{questionId:q.id,lessonId:q.lessonId,correct:selected===q.correctChoiceIndex,confidence}]);setIndex(i=>i+1);setSelected(null);setConfidence(null)}
 return <section className="card"><div className="flex flex-wrap justify-between gap-2"><strong>Economics comprehensive assessment · {index+1}/{list.length}</strong><span aria-live="polite">{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</span><Button onClick={()=>setPaused(x=>!x)}>{paused?'Resume':'Pause'}</Button></div>{paused?<p role="status" className="mt-6 text-center">Assessment paused. Progress is saved on this device.</p>:<div className="mt-5"><QuestionCard question={q} selected={selected} onSelect={setSelected} revealed={revealed}/>{revealed&&<><AnswerExplanation question={q} selected={selected}/><ConfidenceSelector value={confidence} onChange={setConfidence}/><Button className="btn-primary mt-4" disabled={!confidence} onClick={next}>Next</Button></>}</div>}</section>;
}
const shuffle=<T,>(items:T[])=>{const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
